# Generated by Dagster Code Generator
# Generation Metadata:
# - Job Name: fetch_user_data_pipeline
# - Description: No description provided.
# - Executor Type: in_process_executor
# - IO Manager: fs_io_manager
# - Dagster Version: 1.5.0
# - Use Assets: False
# - Required Resources: postgres, reqres

from dagster import job, op, Out, In, RetryPolicy, resource, fs_io_manager, in_process_executor, ScheduleDefinition

@resource
def reqres_api():
    """Resource for interacting with the Reqres API."""
    # Implementation for interacting with the Reqres API
    pass

@resource
def postgres_db():
    """Resource for interacting with the PostgreSQL Database."""
    # Implementation for interacting with the PostgreSQL Database
    pass

@op(required_resource_keys={"reqres_api"}, retry_policy=RetryPolicy(max_retries=0))
def fetch_user_data(context):
    """Fetch user data from the Reqres API."""
    # Implementation to fetch user data from the Reqres API
    user_data = context.resources.reqres_api.get_user_data()
    return user_data

@op(ins={"user_data": In()}, retry_policy=RetryPolicy(max_retries=0))
def process_user_data(context, user_data):
    """Process the fetched user data."""
    # Implementation to process the user data
    processed_data = [user for user in user_data if user['active']]
    return processed_data

@op(ins={"processed_data": In()}, required_resource_keys={"postgres_db"}, retry_policy=RetryPolicy(max_retries=0))
def create_user_table(context, processed_data):
    """Create the user table in the PostgreSQL database."""
    # Implementation to create the user table in the PostgreSQL database
    context.resources.postgres_db.create_table('users', processed_data)

@op(ins={"processed_data": In()}, required_resource_keys={"postgres_db"}, retry_policy=RetryPolicy(max_retries=0))
def insert_user_data(context, processed_data):
    """Insert the processed user data into the PostgreSQL database."""
    # Implementation to insert the processed user data into the PostgreSQL database
    context.resources.postgres_db.insert_data('users', processed_data)

@job(
    name="fetch_user_data_pipeline",
    description="No description provided.",
    executor_def=in_process_executor,
    resource_defs={"reqres_api": reqres_api, "postgres_db": postgres_db, "io_manager": fs_io_manager},
)
def fetch_user_data_pipeline():
    """Dagster job to fetch, process, and store user data."""
    processed_data = process_user_data(fetch_user_data())
    user_table_created = create_user_table(processed_data)
    insert_user_data(user_table_created)

# Schedule the job to run daily
fetch_user_data_pipeline_schedule = ScheduleDefinition(
    job=fetch_user_data_pipeline,
    cron_schedule="@daily",
    execution_timezone="UTC",
    should_execute=lambda _context: True,
    execution_time_window=None,
    name="fetch_user_data_pipeline_schedule",
    description="Schedule to run the fetch_user_data_pipeline daily.",
    tags_fn=lambda _context: {"dagster/schedule_name": "fetch_user_data_pipeline_schedule"},
    job_name="fetch_user_data_pipeline",
    default_status=True,
    execution_timezone="UTC",
    execution_time_window=None,
    should_execute=lambda _context: True,
    tags_fn=lambda _context: {"dagster/schedule_name": "fetch_user_data_pipeline_schedule"},
)