# Generated by Dagster Code Generator
# Generation Metadata:
# - Job Name: load_and_modify_data_pipeline
# - Description: No description provided.
# - Executor Type: docker_executor
# - IO Manager: fs_io_manager
# - Dagster Version: 1.5.0
# - Use Assets: False
# - Required Resources: app_network

from dagster import job, op, Out, In, RetryPolicy, fs_io_manager, Field, String, resource, execute_job, docker_executor

# Resources
@resource(config_schema={"data_dir": Field(String)})
def data_dir(context):
    return context.resource_config["data_dir"]

@resource
def load_and_modify_service():
    pass

@resource
def reconciliation_service():
    pass

@resource
def column_extension_service():
    pass

@resource
def save_service():
    pass

@resource(config_schema={"transport_stops_geojson": Field(String)})
def transport_stops_geojson(context):
    return context.resource_config["transport_stops_geojson"]

@resource(config_schema={"residential_areas_geojson": Field(String)})
def residential_areas_geojson(context):
    return context.resource_config["residential_areas_geojson"]

@resource
def mongodb():
    pass

@resource
def intertwino_api():
    pass

# Ops
@op(
    out={"modified_data": Out()},
    required_resource_keys={"data_dir", "load_and_modify_service"},
    retry_policy=RetryPolicy(max_retries=1),
)
def load_and_modify_data(context):
    """Load and modify data using the load_and_modify_service."""
    data_dir = context.resources.data_dir
    modified_data = context.resources.load_and_modify_service.load_and_modify(data_dir)
    return modified_data

@op(
    out={"reconciled_data": Out()},
    required_resource_keys={"reconciliation_service"},
    retry_policy=RetryPolicy(max_retries=1),
)
def reconcile_geocoding(context, modified_data):
    """Reconcile geocoding using the reconciliation_service."""
    reconciled_data = context.resources.reconciliation_service.reconcile(modified_data)
    return reconciled_data

@op(
    out={"distance_to_pt_data": Out()},
    required_resource_keys={"column_extension_service", "transport_stops_geojson"},
    retry_policy=RetryPolicy(max_retries=1),
)
def calculate_distance_pt(context, reconciled_data):
    """Calculate distance to public transport using the column_extension_service."""
    transport_stops = context.resources.transport_stops_geojson
    distance_to_pt_data = context.resources.column_extension_service.calculate_distance(reconciled_data, transport_stops)
    return distance_to_pt_data

@op(
    out={"distance_to_residential_data": Out()},
    required_resource_keys={"column_extension_service", "residential_areas_geojson"},
    retry_policy=RetryPolicy(max_retries=1),
)
def calculate_distance_residential(context, distance_to_pt_data):
    """Calculate distance to residential areas using the column_extension_service."""
    residential_areas = context.resources.residential_areas_geojson
    distance_to_residential_data = context.resources.column_extension_service.calculate_distance(distance_to_pt_data, residential_areas)
    return distance_to_residential_data

@op(
    required_resource_keys={"save_service"},
    retry_policy=RetryPolicy(max_retries=1),
)
def save_final_data(context, distance_to_residential_data):
    """Save the final data using the save_service."""
    context.resources.save_service.save(distance_to_residential_data)

# Job
@job(
    name="load_and_modify_data_pipeline",
    description="No description provided.",
    executor_def=docker_executor,
    resource_defs={
        "data_dir": data_dir,
        "load_and_modify_service": load_and_modify_service,
        "reconciliation_service": reconciliation_service,
        "column_extension_service": column_extension_service,
        "save_service": save_service,
        "transport_stops_geojson": transport_stops_geojson,
        "residential_areas_geojson": residential_areas_geojson,
        "mongodb": mongodb,
        "intertwino_api": intertwino_api,
        "io_manager": fs_io_manager,
    },
)
def load_and_modify_data_pipeline():
    modified_data = load_and_modify_data()
    reconciled_data = reconcile_geocoding(modified_data)
    distance_to_pt_data = calculate_distance_pt(reconciled_data)
    distance_to_residential_data = calculate_distance_residential(distance_to_pt_data)
    save_final_data(distance_to_residential_data)