# Generated by Dagster Code Generator
# Generation Metadata:
# - Job Name: wait_for_sales_aggregation_pipeline
# - Description: No description provided.
# - Executor Type: in_process_executor
# - IO Manager: fs_io_manager
# - Dagster Version: 1.5.0
# - Use Assets: False
# - Required Resources: ["daily_sales_aggregation"]

from dagster import job, op, In, Out, RetryPolicy, fs_io_manager, resource, in_process_executor, daily_schedule

@resource
def daily_sales_aggregation_dag():
    """Resource for the Daily Sales Aggregation DAG."""
    pass

@op(
    name="wait_for_sales_aggregation",
    description="Wait for Sales Aggregation",
    retry_policy=RetryPolicy(max_retries=0),
    required_resource_keys={"daily_sales_aggregation_dag"}
)
def wait_for_sales_aggregation(context):
    """Wait for the sales aggregation to complete."""
    context.log.info("Waiting for sales aggregation to complete.")
    # Simulate waiting for the aggregation to complete
    context.log.info("Sales aggregation completed.")

@op(
    name="load_sales_csv",
    description="Load Sales CSV",
    retry_policy=RetryPolicy(max_retries=2),
    ins={"aggregation_complete": In()},
    out=Out(io_manager_key="sales_csv_data")
)
def load_sales_csv(context, aggregation_complete):
    """Load the sales CSV data."""
    context.log.info("Loading sales CSV data.")
    # Simulate loading CSV data
    context.log.info("Sales CSV data loaded.")

@op(
    name="generate_dashboard",
    description="Generate Dashboard",
    retry_policy=RetryPolicy(max_retries=2),
    ins={"sales_data": In(io_manager_key="sales_csv_data")},
    out=Out(io_manager_key="dashboard_output")
)
def generate_dashboard(context, sales_data):
    """Generate the dashboard from the sales data."""
    context.log.info("Generating dashboard.")
    # Simulate generating the dashboard
    context.log.info("Dashboard generated.")

@job(
    name="wait_for_sales_aggregation_pipeline",
    description="No description provided.",
    executor_def=in_process_executor,
    resource_defs={
        "daily_sales_aggregation_dag": daily_sales_aggregation_dag,
        "sales_csv_data": fs_io_manager,
        "dashboard_output": fs_io_manager
    }
)
def wait_for_sales_aggregation_pipeline():
    """Dagster job for the wait_for_sales_aggregation_pipeline."""
    sales_data = load_sales_csv(wait_for_sales_aggregation())
    generate_dashboard(sales_data)

@daily_schedule(
    pipeline_name="wait_for_sales_aggregation_pipeline",
    start_date="2023-01-01",
    execution_time="00:00",
    execution_timezone="UTC",
    name="wait_for_sales_aggregation_pipeline_schedule",
    description="Daily schedule for the wait_for_sales_aggregation_pipeline.",
    cron_schedule="@daily",
    catchup=False
)
def wait_for_sales_aggregation_pipeline_schedule(date):
    return {}