# Generated by Dagster Code Generator
# Date: 2023-10-05
# Dagster Version: 1.5.0

from dagster import (
    job,
    op,
    In,
    Out,
    RetryPolicy,
    ResourceDefinition,
    fs_io_manager,
    in_process_executor,
    schedule,
)

# Resources
airflow_metastore = ResourceDefinition.mock_resource()
airflow_variables = ResourceDefinition.mock_resource()
xcom = ResourceDefinition.mock_resource()

# Ops
@op(
    required_resource_keys={"airflow_variables"},
    out={"config_data": Out()},
    retry_policy=RetryPolicy(max_retries=1),
)
def print_configuration(context):
    """
    Print Configuration Op
    """
    config_data = context.resources.airflow_variables.get("config_data")
    context.log.info(f"Configuration: {config_data}")
    return config_data

@op(
    required_resource_keys={"airflow_metastore"},
    in_={"config_data": In()},
    retry_policy=RetryPolicy(max_retries=1),
)
def cleanup_airflow_metadb(context, config_data):
    """
    Cleanup Airflow MetaDB Op
    """
    context.log.info(f"Cleaning up Airflow MetaDB with config: {config_data}")
    # Perform cleanup logic here
    context.resources.airflow_metastore.cleanup()

# Job
@job(
    name="print_configuration_pipeline",
    description="No description provided.",
    executor_def=in_process_executor,
    resource_defs={
        "airflow_metastore": airflow_metastore,
        "airflow_variables": airflow_variables,
        "io_manager": fs_io_manager,
    },
)
def print_configuration_pipeline():
    """
    Print Configuration Pipeline
    """
    config_data = print_configuration()
    cleanup_airflow_metadb(config_data)

# Schedule
@schedule(
    job=print_configuration_pipeline,
    cron_schedule="@daily",
    execution_timezone="UTC",
    name="print_configuration_pipeline_schedule",
    catchup=False,
)
def print_configuration_pipeline_schedule(_context):
    return {}