# Generated by Airflow DAG Code Generator
# Date: 2023-10-05
# Airflow Version: 2.x

from airflow import DAG
from airflow.providers.docker.operators.docker import DockerOperator
from airflow.utils.dates import days_ago
from airflow.utils.task_group import TaskGroup
from datetime import timedelta

# Default arguments for the DAG
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

# Define the DAG
with DAG(
    dag_id='load_and_modify_data_pipeline',
    default_args=default_args,
    schedule_interval=None,
    start_date=days_ago(1),
    catchup=False,
    tags=['data_pipeline'],
) as dag:

    # Task: Load and Modify Data
    load_and_modify_data = DockerOperator(
        task_id='load_and_modify_data',
        image='i2t-backendwithintertwino6-load-and-modify:latest',
        environment={
            'DATASET_ID': 2,
            'TABLE_NAME_PREFIX': 'JOT_'
        },
        retries=1,
        dag=dag,
    )

    # Task: Reconcile Geocoding
    reconcile_geocoding = DockerOperator(
        task_id='reconcile_geocoding',
        image='i2t-backendwithintertwino6-reconciliation:latest',
        environment={
            'PRIMARY_COLUMN': 'address',
            'RECONCILIATOR_ID': 'geocodingHere',
            'API_TOKEN': '[HERE API token]',
            'DATASET_ID': 2
        },
        retries=1,
        dag=dag,
    )

    # Task: Calculate Distance to Public Transport
    calculate_distance_pt = DockerOperator(
        task_id='calculate_distance_pt',
        image='i2t-backendwithintertwino6-column-extension:latest',
        environment={
            'EXTENDER_ID': 'spatialDistanceCalculator',
            'LAT_COLUMN': 'latitude',
            'LON_COLUMN': 'longitude',
            'TARGET_LAYER': 'public_transport',
            'TARGET_DATA_SOURCE': '/app/data/transport_stops.geojson',
            'OUTPUT_COLUMN': 'distance_to_pt',
            'DATASET_ID': 2
        },
        retries=1,
        dag=dag,
    )

    # Task: Calculate Distance to Residential Areas
    calculate_distance_residential = DockerOperator(
        task_id='calculate_distance_residential',
        image='i2t-backendwithintertwino6-column-extension:latest',
        environment={
            'EXTENDER_ID': 'spatialDistanceCalculator',
            'LAT_COLUMN': 'latitude',
            'LON_COLUMN': 'longitude',
            'TARGET_LAYER': 'residential_areas',
            'TARGET_DATA_SOURCE': '/app/data/residential_areas.geojson',
            'OUTPUT_COLUMN': 'distance_to_residential',
            'DATASET_ID': 2
        },
        retries=1,
        dag=dag,
    )

    # Task: Save Final Data
    save_final_data = DockerOperator(
        task_id='save_final_data',
        image='i2t-backendwithintertwino6-save:latest',
        environment={
            'DATASET_ID': 2
        },
        retries=1,
        dag=dag,
    )

    # Define task dependencies
    load_and_modify_data >> reconcile_geocoding >> calculate_distance_pt >> calculate_distance_residential >> save_final_data