# Generated by Dagster Pipeline Generator
# Date: 2024-06-28
# Pipeline: Backup Strategy Selector

from datetime import datetime
from typing import Optional

from dagster import (
    op,
    job,
    In,
    Out,
    RetryPolicy,
    ScheduleDefinition,
    DefaultScheduleStatus,
    Definitions,
    fs_io_manager,
    in_process_executor,
)


@op(
    name="start_backup_process",
    description="Initial step that records the start time of the backup workflow.",
    out=Out(datetime, description="Timestamp when the backup process started."),
    retry_policy=RetryPolicy(max_retries=0),
)
def start_backup_process() -> datetime:
    """Emit the current UTC timestamp to signal the start of the backup pipeline."""
    return datetime.utcnow()


@op(
    name="determine_backup_strategy",
    description="Selects a backup strategy (full or incremental) based on the day of week.",
    ins={"start_time": In(datetime)},
    out=Out(str, description="Chosen strategy: 'full' or 'incremental'."),
    retry_policy=RetryPolicy(max_retries=2),
)
def determine_backup_strategy(start_time: datetime) -> str:
    """Return 'full' on Mondays, otherwise 'incremental'."""
    # Monday is 0 in Python's weekday()
    if start_time.weekday() == 0:
        return "full"
    return "incremental"


@op(
    name="perform_full_backup",
    description="Executes a full backup when the selected strategy is 'full'.",
    ins={"strategy": In(str)},
    out=Out(Optional[str], description="Result message or None if not executed."),
    retry_policy=RetryPolicy(max_retries=2),
)
def perform_full_backup(strategy: str) -> Optional[str]:
    """Run a full backup only if the strategy is 'full'."""
    if strategy != "full":
        return None
    # Placeholder for actual backup logic
    return "Full backup completed successfully."


@op(
    name="perform_incremental_backup",
    description="Executes an incremental backup when the selected strategy is 'incremental'.",
    ins={"strategy": In(str)},
    out=Out(Optional[str], description="Result message or None if not executed."),
    retry_policy=RetryPolicy(max_retries=2),
)
def perform_incremental_backup(strategy: str) -> Optional[str]:
    """Run an incremental backup only if the strategy is 'incremental'."""
    if strategy != "incremental":
        return None
    # Placeholder for actual backup logic
    return "Incremental backup completed successfully."


@op(
    name="verify_backup",
    description="Verifies the outcome of whichever backup operation was performed.",
    ins={
        "full_result": In(Optional[str]),
        "incremental_result": In(Optional[str]),
    },
    out=Out(bool, description="True if verification succeeded, False otherwise."),
    retry_policy=RetryPolicy(max_retries=2),
)
def verify_backup(
    full_result: Optional[str], incremental_result: Optional[str]
) -> bool:
    """Simple verification that checks the backup result string."""
    result = full_result or incremental_result
    if result is None:
        # No backup was performed; treat as failure
        return False
    # In a real scenario, more sophisticated checks would be performed here
    return "completed successfully" in result.lower()


@op(
    name="finalize_backup",
    description="Final step that records the verification outcome and performs cleanup.",
    ins={"verification_passed": In(bool)},
    out=Out(str, description="Final status message."),
    retry_policy=RetryPolicy(max_retries=2),
)
def finalize_backup(verification_passed: bool) -> str:
    """Emit a final status based on verification outcome."""
    if verification_passed:
        return "Backup workflow completed and verified."
    return "Backup workflow failed verification."


@job(
    name="backup_strategy_selector",
    description=(
        "Comprehensive pipeline that selects a backup strategy (full or incremental) "
        "based on the day of week, using a branch‑merge pattern."
    ),
    executor_def=in_process_executor,
    resource_defs={"io_manager": fs_io_manager},
)
def backup_strategy_selector():
    """Orchestrates the backup workflow using a fan‑out/fan‑in pattern."""
    start_time = start_backup_process()
    strategy = determine_backup_strategy(start_time)

    # Fan‑out: both backup ops receive the strategy, but only one will act.
    full_result = perform_full_backup(strategy)
    incremental_result = perform_incremental_backup(strategy)

    # Fan‑in: verification waits for both possible backup results.
    verification = verify_backup(full_result, incremental_result)

    # Final step
    finalize_backup(verification)


daily_backup_schedule = ScheduleDefinition(
    job=backup_strategy_selector,
    cron_schedule="0 0 * * *",  # @daily at 00:00 UTC
    execution_timezone="UTC",
    default_status=DefaultScheduleStatus.RUNNING,
    description="Runs the backup strategy selector pipeline daily at midnight UTC.",
)


defs = Definitions(
    jobs=[backup_strategy_selector],
    schedules=[daily_backup_schedule],
    resources={"io_manager": fs_io_manager},
)