# Generated by Prefect 2.x Code Generator
# Date: 2023-10-05
# Prefect Version: 2.14.0

from prefect import flow, task, get_run_logger
from prefect.task_runners import SequentialTaskRunner
from prefect.blocks.system import Secret, LocalFileSystem
from prefect.infrastructure.docker import DockerContainer
from prefect.infrastructure.process import Process
from prefect.blocks.notifications import EmailNotificationBlock
import json

# Load secrets and resources
mahidol_aqi_website = Secret.load("mahidol-aqi-website")
local_filesystem = LocalFileSystem.load("local-filesystem")
postgres_conn = Secret.load("postgres-conn")
smtp_server = Secret.load("smtp-server")
config_files = LocalFileSystem.load("config-files")

@task(retries=0, name="Get Mahidol AQI Report")
def get_data_mahidol_aqi_report():
    logger = get_run_logger()
    logger.info("Fetching data from Mahidol AQI website...")
    # Placeholder for actual data fetching logic
    data = {"aqi": 50, "location": "Bangkok", "timestamp": "2023-10-05T12:00:00Z"}
    logger.info("Data fetched successfully.")
    return data

@task(retries=0, name="Create JSON Object")
def create_json_object(data):
    logger = get_run_logger()
    logger.info("Creating JSON object...")
    json_data = json.dumps(data)
    logger.info("JSON object created successfully.")
    return json_data

@task(retries=0, name="Load Mahidol AQI to PostgreSQL")
def load_mahidol_aqi_to_postgres(json_data):
    logger = get_run_logger()
    logger.info("Loading data to PostgreSQL...")
    # Placeholder for actual database loading logic
    logger.info("Data loaded successfully.")
    return True

@task(retries=0, name="Send Email Alert")
def alert_email():
    logger = get_run_logger()
    logger.info("Sending email alert...")
    # Placeholder for actual email sending logic
    email_block = EmailNotificationBlock.load("smtp-server")
    email_block.notify("Mahidol AQI Report", "The AQI report has been successfully processed.")
    logger.info("Email alert sent successfully.")
    return True

@flow(name="get_data_mahidol_aqi_report_pipeline", task_runner=SequentialTaskRunner())
def get_data_mahidol_aqi_report_pipeline():
    logger = get_run_logger()
    logger.info("Starting Mahidol AQI Report Pipeline...")

    data = get_data_mahidol_aqi_report()
    json_data = create_json_object(data)
    load_status = load_mahidol_aqi_to_postgres(json_data)
    alert_email()

if __name__ == "__main__":
    get_data_mahidol_aqi_report_pipeline()