# Generated by Prefect 2.x Code Generator
# Date: 2023-10-05
# Prefect Version: 2.14.0

from prefect import flow, task, get_run_logger
from prefect.task_runners import ConcurrentTaskRunner
from prefect.deployments import Deployment
from prefect.filesystems import LocalFileSystem
from prefect.blocks.system import Secret
from prefect.infrastructure.docker import DockerContainer
from prefect import flow, task
from prefect.tasks import task_input_hash
from datetime import timedelta
import os

# Load the file systems and secrets
us_east_data_source = LocalFileSystem.load("us-east-data-source")
us_west_data_source = LocalFileSystem.load("us-west-data-source")
eu_data_source = LocalFileSystem.load("eu-data-source")
apac_data_source = LocalFileSystem.load("apac-data-source")
xcom = Secret.load("xcom")

# Define the tasks
@task(retries=0, name="Start Pipeline")
def start_pipeline():
    """Start the pipeline."""
    logger = get_run_logger()
    logger.info("Pipeline started.")
    return True

@task(retries=2, name="Ingest APAC Sales Data")
def ingest_apac():
    """Ingest APAC sales data."""
    logger = get_run_logger()
    logger.info("Ingesting APAC sales data.")
    # Simulate data ingestion
    apac_data_source.read_path("apac_sales_data.csv")
    return True

@task(retries=2, name="Ingest EU Sales Data")
def ingest_eu():
    """Ingest EU sales data."""
    logger = get_run_logger()
    logger.info("Ingesting EU sales data.")
    # Simulate data ingestion
    eu_data_source.read_path("eu_sales_data.csv")
    return True

@task(retries=2, name="Ingest US-East Sales Data")
def ingest_us_east():
    """Ingest US-East sales data."""
    logger = get_run_logger()
    logger.info("Ingesting US-East sales data.")
    # Simulate data ingestion
    us_east_data_source.read_path("us_east_sales_data.csv")
    return True

@task(retries=2, name="Ingest US-West Sales Data")
def ingest_us_west():
    """Ingest US-West sales data."""
    logger = get_run_logger()
    logger.info("Ingesting US-West sales data.")
    # Simulate data ingestion
    us_west_data_source.read_path("us_west_sales_data.csv")
    return True

@task(retries=2, name="Convert APAC Currency to USD")
def convert_currency_apac():
    """Convert APAC currency to USD."""
    logger = get_run_logger()
    logger.info("Converting APAC currency to USD.")
    # Simulate currency conversion
    return True

@task(retries=2, name="Convert EU Currency to USD")
def convert_currency_eu():
    """Convert EU currency to USD."""
    logger = get_run_logger()
    logger.info("Converting EU currency to USD.")
    # Simulate currency conversion
    return True

@task(retries=2, name="Convert US-East Currency to USD")
def convert_currency_us_east():
    """Convert US-East currency to USD."""
    logger = get_run_logger()
    logger.info("Converting US-East currency to USD.")
    # Simulate currency conversion
    return True

@task(retries=2, name="Convert US-West Currency to USD")
def convert_currency_us_west():
    """Convert US-West currency to USD."""
    logger = get_run_logger()
    logger.info("Converting US-West currency to USD.")
    # Simulate currency conversion
    return True

@task(retries=2, name="Aggregate Global Revenue")
def aggregate_global_revenue():
    """Aggregate global revenue."""
    logger = get_run_logger()
    logger.info("Aggregating global revenue.")
    # Simulate revenue aggregation
    return True

@task(retries=0, name="End Pipeline")
def end_pipeline():
    """End the pipeline."""
    logger = get_run_logger()
    logger.info("Pipeline ended.")
    return True

# Define the flow
@flow(name="start_pipeline_pipeline", task_runner=ConcurrentTaskRunner(), retries=0)
def start_pipeline_pipeline():
    """Main pipeline flow."""
    start = start_pipeline()
    ingest_us_east_result = ingest_us_east(wait_for=[start])
    ingest_us_west_result = ingest_us_west(wait_for=[start])
    ingest_eu_result = ingest_eu(wait_for=[start])
    ingest_apac_result = ingest_apac(wait_for=[start])

    convert_currency_us_east_result = convert_currency_us_east(wait_for=[ingest_us_east_result])
    convert_currency_us_west_result = convert_currency_us_west(wait_for=[ingest_us_west_result])
    convert_currency_eu_result = convert_currency_eu(wait_for=[ingest_eu_result])
    convert_currency_apac_result = convert_currency_apac(wait_for=[ingest_apac_result])

    aggregate_global_revenue_result = aggregate_global_revenue(
        wait_for=[convert_currency_us_east_result, convert_currency_us_west_result, convert_currency_eu_result, convert_currency_apac_result]
    )

    end_pipeline_result = end_pipeline(wait_for=[aggregate_global_revenue_result])

# Define the deployment
deployment = Deployment.build_from_flow(
    flow=start_pipeline_pipeline,
    name="start_pipeline_pipeline_deployment",
    work_pool_name="default-agent-pool",
    schedule=(None, "@daily", "UTC", False),
    parameters={},
    tags=[],
    work_queue_name="default",
    version="1.0.0",
    description="No description provided.",
    path=".",
    entrypoint="pipeline.py:start_pipeline_pipeline",
    parameter_openapi_schema={},
)

if __name__ == "__main__":
    deployment.apply()