# Generated by Dagster Code Generator
# Date: 2023-10-05
# Dagster Version: 1.5.0

from dagster import (
    job,
    op,
    Out,
    In,
    RetryPolicy,
    multiprocess_executor,
    fs_io_manager,
    resource,
    schedule,
    ScheduleEvaluationContext,
)

# Resources
@resource
def raw_csv_source():
    """Resource for accessing the raw CSV source."""
    pass

@resource
def production_database():
    """Resource for accessing the production database."""
    pass

@resource
def quarantine_storage():
    """Resource for accessing the quarantine storage."""
    pass

@resource
def email_system():
    """Resource for accessing the email system."""
    pass

# Ops
@op(
    out={"csv_data": Out()},
    required_resource_keys={"raw_csv_source"},
    retry_policy=RetryPolicy(max_retries=1),
)
def ingest_csv(context):
    """Ingest CSV data from the raw CSV source."""
    csv_data = context.resources.raw_csv_source.load_csv()
    return csv_data

@op(
    in_={"csv_data": In()},
    out={"quality_check_result": Out()},
    required_resource_keys={"quarantine_storage"},
    retry_policy=RetryPolicy(max_retries=1),
)
def quality_check(context, csv_data):
    """Perform quality checks on the ingested CSV data."""
    quality_check_result = context.resources.quarantine_storage.check_quality(csv_data)
    return quality_check_result

@op(
    in_={"quality_check_result": In()},
    out={"load_result": Out()},
    required_resource_keys={"production_database"},
    retry_policy=RetryPolicy(max_retries=1),
)
def production_load(context, quality_check_result):
    """Load the CSV data into the production database."""
    load_result = context.resources.production_database.load_data(quality_check_result)
    return load_result

@op(
    in_={"quality_check_result": In()},
    out={"quarantine_result": Out()},
    required_resource_keys={"quarantine_storage"},
    retry_policy=RetryPolicy(max_retries=1),
)
def quarantine_and_alert(context, quality_check_result):
    """Quarantine the CSV data and alert the system."""
    quarantine_result = context.resources.quarantine_storage.quarantine_data(quality_check_result)
    return quarantine_result

@op(
    in_={"quarantine_result": In()},
    out={"alert_result": Out()},
    required_resource_keys={"email_system"},
    retry_policy=RetryPolicy(max_retries=1),
)
def send_alert_email(context, quarantine_result):
    """Send an alert email."""
    alert_result = context.resources.email_system.send_alert(quarantine_result)
    return alert_result

@op(
    in_={
        "load_result": In(),
        "alert_result": In(),
    },
    out={"cleanup_result": Out()},
    retry_policy=RetryPolicy(max_retries=1),
)
def cleanup(context, load_result, alert_result):
    """Perform cleanup operations."""
    cleanup_result = context.resources.file_system.cleanup(load_result, alert_result)
    return cleanup_result

# Job
@job(
    name="ingest_csv_pipeline",
    description="No description provided.",
    executor_def=multiprocess_executor,
    resource_defs={
        "raw_csv_source": raw_csv_source,
        "production_database": production_database,
        "quarantine_storage": quarantine_storage,
        "email_system": email_system,
        "file_system": fs_io_manager,
    },
)
def ingest_csv_pipeline():
    """Ingest CSV data, perform quality checks, load into production, quarantine and alert, and clean up."""
    csv_data = ingest_csv()
    quality_check_result = quality_check(csv_data)
    load_result = production_load(quality_check_result)
    quarantine_result = quarantine_and_alert(quality_check_result)
    alert_result = send_alert_email(quarantine_result)
    cleanup(load_result, alert_result)

# Schedule
@schedule(
    job=ingest_csv_pipeline,
    cron_schedule="@daily",
    execution_timezone="UTC",
    name="ingest_csv_pipeline_schedule",
    catchup=False,
)
def ingest_csv_pipeline_schedule(context: ScheduleEvaluationContext):
    """Schedule the ingest_csv_pipeline to run daily."""
    return {}