# Generated by Dagster code generator
# Date: 2024-06-28
# Pipeline: PM2.5_Risk_Alert_Pipeline
# Description: Sequential ETL pipeline that scrapes Mahidol University AQI data,
# transforms it to JSON, loads it into PostgreSQL, and sends email alerts when
# PM2.5 exceeds thresholds.

from __future__ import annotations

import json
import logging
from typing import Any, Dict, List, Optional

import dagster
from dagster import (
    Config,
    In,
    Out,
    RetryPolicy,
    String,
    asset,
    job,
    op,
    resource,
    Field,
    StringSource,
    Bool,
    Int,
    Nothing,
    Output,
    RetryRequested,
    get_dagster_logger,
)
from dagster import In, Out, op, job, RetryPolicy, resource, ConfigurableResource
from dagster import fs_io_manager, InProcessExecutor

logger = get_dagster_logger(__name__)

# -------------------------------------------------------------------------
# Resource definitions
# -------------------------------------------------------------------------

@resource(config_schema={"base_url": String})
def mahidol_aqi_website_api(init_context: dagster.InitResourceContext) -> Any:
    """Simple HTTP client for the Mahidol University AQI website.

    The real implementation would use ``requests`` or ``httpx`` to fetch the HTML.
    """
    class MahidolAQIClient:
        def __init__(self, base_url: str) -> None:
            self.base_url = base_url.rstrip("/")

        def fetch_html(self) -> str:
            # Placeholder implementation – replace with real HTTP request.
            logger.info(f"Fetching AQI HTML from {self.base_url}")
            return "<html><body><div id='aqi'>PM2.5: 85 µg/m³</div></body></html>"

    return MahidolAQIClient(base_url=init_context.resource_config["base_url"])


@resource(config_schema={"connection_string": String})
def postgres_warehouse(init_context: dagster.InitResourceContext) -> Any:
    """PostgreSQL connection resource.

    In production this would return a SQLAlchemy engine or psycopg2 connection.
    """
    class PostgresClient:
        def __init__(self, conn_str: str) -> None:
            self.conn_str = conn_str

        def insert_aqi(self, data: Dict[str, Any]) -> None:
            # Placeholder – replace with actual INSERT logic.
            logger.info(f"Inserting AQI data into PostgreSQL: {json.dumps(data)}")

    return PostgresClient(connection_string=init_context.resource_config["connection_string"])


@resource(config_schema={"smtp_server": String, "port": Int, "username": String, "password": String})
def smtp_gmail(init_context: dagster.InitResourceContext) -> Any:
    """SMTP client for Gmail.

    A real implementation would use ``smtplib`` or a third‑party library.
    """
    class SMTPClient:
        def __init__(self, server: str, port: int, user: str, pwd: str) -> None:
            self.server = server
            self.port = port
            self.user = user
            self.pwd = pwd

        def send_email(self, subject: str, body: str, to: List[str]) -> None:
            # Placeholder – replace with actual email sending.
            logger.info(
                f"Sending email via Gmail SMTP to {to}: subject='{subject}', body='{body}'"
            )

    cfg = init_context.resource_config
    return SMTPClient(
        server=cfg["smtp_server"],
        port=cfg["port"],
        user=cfg["username"],
        pwd=cfg["password"],
    )


# -------------------------------------------------------------------------
# Op definitions
# -------------------------------------------------------------------------

@op(
    name="Extract Mahidol AQI HTML",
    description="Scrape the Mahidol University AQI website and return raw HTML.",
    out=Out(String),
    required_resource_keys={"mahidol_aqi_website_api"},
    retry_policy=RetryPolicy(max_retries=0),
)
def extract_mahidol_aqi_html(context: dagster.OpContext) -> str:
    client = context.resources.mahidol_aqi_website_api
    html = client.fetch_html()
    context.log.info("Fetched HTML content (truncated to 200 chars).")
    return html[:200]  # Return a truncated version for downstream ops


@op(
    name="Transform HTML to Structured JSON",
    description="Parse the raw HTML and produce a structured JSON payload.",
    ins={"html": In(String)},
    out=Out(Dict[str, Any]),
    retry_policy=RetryPolicy(max_retries=0),
)
def transform_html_to_json(context: dagster.OpContext, html: str) -> Dict[str, Any]:
    """
    Very simple parser – in a real pipeline you would use BeautifulSoup or lxml.
    Expected output format:
    {
        "pm25": float,
        "timestamp": "ISO8601 string",
        "source": "Mahidol University"
    }
    """
    import re
    from datetime import datetime, timezone

    # Extract a numeric PM2.5 value from the placeholder HTML.
    match = re.search(r"PM2\.5:\s*([\d.]+)", html)
    pm25 = float(match.group(1)) if match else -1.0

    payload = {
        "pm25": pm25,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "source": "Mahidol University",
    }
    context.log.info(f"Transformed payload: {payload}")
    return payload


@op(
    name="Load AQI Data to PostgreSQL Warehouse",
    description="Insert the structured AQI JSON into the PostgreSQL data warehouse.",
    ins={"aqi_data": In(Dict[str, Any])},
    out=Out(Nothing),
    required_resource_keys={"postgres_warehouse"},
    retry_policy=RetryPolicy(max_retries=0),
)
def load_mahidol_aqi_to_warehouse(context: dagster.OpContext, aqi_data: Dict[str, Any]) -> Nothing:
    client = context.resources.postgres_warehouse
    client.insert_aqi(aqi_data)
    context.log.info("AQI data loaded into PostgreSQL.")
    return Nothing


class NotifyConfig(Config):
    """Configuration for the email alert operation."""

    pm25_threshold: float = Field(
        default_value=75.0,
        description="PM2.5 concentration threshold that triggers an email alert.",
    )
    recipients: List[str] = Field(
        default_value=["alert@example.com"],
        description="List of email addresses to notify.",
    )
    subject_template: str = Field(
        default_value="PM2.5 Alert: {pm25} µg/m³",
        description="Subject line template for the alert email.",
    )
    body_template: str = Field(
        default_value=(
            "The latest PM2.5 measurement from Mahidol University is {pm25} µg/m³ "
            "recorded at {timestamp}. Please take appropriate actions."
        ),
        description="Body template for the alert email.",
    )


@op(
    name="PM2.5 Email Alert Notification",
    description="Send an email alert if the PM2.5 value exceeds the configured threshold.",
    ins={"aqi_data": In(Dict[str, Any])},
    out=Out(Nothing),
    required_resource_keys={"smtp_gmail"},
    retry_policy=RetryPolicy(max_retries=0),
    config_schema=NotifyConfig,
)
def notify_pm25_alert(context: dagster.OpContext, aqi_data: Dict[str, Any]) -> Nothing:
    cfg: NotifyConfig = context.op_config
    pm25 = aqi_data.get("pm25", 0.0)

    if pm25 <= cfg.pm25_threshold:
        context.log.info(
            f"PM2.5 value {pm25} µg/m³ is below threshold {cfg.pm25_threshold}. No email sent."
        )
        return Nothing

    subject = cfg.subject_template.format(pm25=pm25)
    body = cfg.body_template.format(pm25=pm25, timestamp=aqi_data.get("timestamp", "N/A"))

    smtp_client = context.resources.smtp_gmail
    smtp_client.send_email(subject=subject, body=body, to=cfg.recipients)

    context.log.info(f"Alert email sent to {cfg.recipients}.")
    return Nothing


# -------------------------------------------------------------------------
# Job definition
# -------------------------------------------------------------------------

@job(
    name="PM2.5_Risk_Alert_Pipeline",
    description=(
        "Sequential ETL pipeline that scrapes Mahidol University AQI data, "
        "transforms it to JSON, loads it into PostgreSQL, and sends email alerts "
        "when PM2.5 exceeds thresholds."
    ),
    executor_def=InProcessExecutor(),
    resource_defs={
        "mahidol_aqi_website_api": mahidol_aqi_website_api,
        "local_filesystem": fs_io_manager,
        "postgres_warehouse": postgres_warehouse,
        "smtp_gmail": smtp_gmail,
    },
    config={
        "resources": {
            "mahidol_aqi_website_api": {"config": {"base_url": "https://aqi.mahidol.ac.th"}},
            "postgres_warehouse": {
                "config": {"connection_string": "postgresql://user:pwd@localhost:5432/warehouse"}
            },
            "smtp_gmail": {
                "config": {
                    "smtp_server": "smtp.gmail.com",
                    "port": 587,
                    "username": "your.email@gmail.com",
                    "password": "your_app_password",
                }
            },
        },
        "ops": {
            "notify_pm25_alert": {
                "config": {
                    "pm25_threshold": 75.0,
                    "recipients": ["alert@example.com"],
                }
            }
        },
    },
)
def pm2_5_risk_alert_pipeline():
    """Orchestrates the sequential ETL steps."""
    html = extract_mahidol_aqi_html()
    aqi_json = transform_html_to_json(html)
    load_mahidol_aqi_to_warehouse(aqi_json)
    notify_pm25_alert(aqi_json)


# -------------------------------------------------------------------------
# Schedule (disabled)
# -------------------------------------------------------------------------

# The schedule is intentionally disabled per specification.
# To enable, uncomment and adjust the cron expression as needed.

# from dagster import schedule

# @schedule(
#     cron_schedule="0 * * * *",  # Example: run hourly
#     job=pm2_5_risk_alert_pipeline,
#     execution_timezone="UTC",
#     default_status=dagster.ScheduleStatus.STOPPED,
# )
# def pm2_5_risk_alert_schedule(_context):
#     return {}

# End of file.