# Generated by Dagster Code Generator
# Generation Metadata:
# - Job Name: fetch_brokerage_holdings_pipeline
# - Description: No description provided.
# - Executor Type: multiprocess_executor
# - IO Manager: fs_io_manager
# - Dagster Version: 1.5.0
# - Use Assets: False
# - Required Resources: mock_brokerage_api

from dagster import (
    job,
    op,
    Out,
    In,
    RetryPolicy,
    multiprocess_executor,
    fs_io_manager,
    resource,
)

@resource
def mock_brokerage_api():
    """Mock Brokerage API resource."""
    pass

@op(
    out=Out(dict),
    retry_policy=RetryPolicy(max_retries=2),
    required_resource_keys={"mock_brokerage_api"},
)
def fetch_brokerage_holdings(context):
    """Fetch Brokerage Holdings from the mock brokerage API."""
    # Mock implementation
    return {"holdings": []}

@op(
    ins={"holdings": In(dict)},
    out=Out(dict),
    retry_policy=RetryPolicy(max_retries=2),
)
def analyze_portfolio(context, holdings):
    """Analyze the portfolio based on the fetched holdings."""
    # Mock implementation
    return {"portfolio_analysis": {}}

@op(
    ins={"portfolio_analysis": In(dict)},
    out=Out(dict),
    retry_policy=RetryPolicy(max_retries=2),
)
def aggregate_and_rebalance(context, portfolio_analysis):
    """Aggregate and rebalance the portfolio based on the analysis."""
    # Mock implementation
    return {"rebalanced_portfolio": {}}

@op(
    ins={"rebalanced_portfolio": In(dict)},
    out=Out(dict),
    retry_policy=RetryPolicy(max_retries=2),
)
def generate_trade_orders(context, rebalanced_portfolio):
    """Generate trade orders based on the rebalanced portfolio."""
    # Mock implementation
    return {"trade_orders": []}

@job(
    name="fetch_brokerage_holdings_pipeline",
    description="No description provided.",
    executor_def=multiprocess_executor,
    resource_defs={"mock_brokerage_api": mock_brokerage_api, "io_manager": fs_io_manager},
)
def fetch_brokerage_holdings_pipeline():
    """Dagster job to fetch brokerage holdings, analyze the portfolio, aggregate and rebalance, and generate trade orders."""
    fetch_1 = fetch_brokerage_holdings.alias("fetch_1")
    fetch_2 = fetch_brokerage_holdings.alias("fetch_2")
    fetch_3 = fetch_brokerage_holdings.alias("fetch_3")
    fetch_4 = fetch_brokerage_holdings.alias("fetch_4")
    fetch_5 = fetch_brokerage_holdings.alias("fetch_5")

    analyze_1 = analyze_portfolio.alias("analyze_1")
    analyze_2 = analyze_portfolio.alias("analyze_2")
    analyze_3 = analyze_portfolio.alias("analyze_3")
    analyze_4 = analyze_portfolio.alias("analyze_4")
    analyze_5 = analyze_portfolio.alias("analyze_5")

    aggregate = aggregate_and_rebalance.alias("aggregate")

    generate = generate_trade_orders.alias("generate")

    fetch_1_out = fetch_1()
    fetch_2_out = fetch_2()
    fetch_3_out = fetch_3()
    fetch_4_out = fetch_4()
    fetch_5_out = fetch_5()

    analyze_1(fetch_1_out)
    analyze_2(fetch_2_out)
    analyze_3(fetch_3_out)
    analyze_4(fetch_4_out)
    analyze_5(fetch_5_out)

    aggregate(analyze_1(), analyze_2(), analyze_3(), analyze_4(), analyze_5())

    generate(aggregate())