# Generated by Prefect 2.x Code Generator
# Date: [Current Date]
# Prefect Version: 2.14.0

from prefect import flow, task, get_run_logger
from prefect.task_runners import SequentialTaskRunner
from prefect.blocks.system import Secret
from prefect.infrastructure import Process
from prefect.deployments import DeploymentSpec
from prefect.orion.schemas.schedules import CronSchedule
from prefect.blocks.notifications import SlackWebhook

# Load secrets
snowflake_conn = Secret.load("snowflake-conn")
slack_conn = Secret.load("slack-conn")

@task(retries=0, name="Run CTAS")
def run_ctas():
    """
    Task to run a CTAS (Create Table As Select) query.
    """
    logger = get_run_logger()
    logger.info("Running CTAS query...")
    # Example CTAS query (replace with actual query)
    ctas_query = "CREATE TABLE new_table AS SELECT * FROM source_table;"
    # Execute the query using the Snowflake connection
    # Example: snowflake_conn.run_query(ctas_query)
    logger.info("CTAS query executed successfully.")

@flow(name="run_ctas_pipeline", task_runner=SequentialTaskRunner)
def run_ctas_pipeline():
    """
    Prefect flow to run the CTAS pipeline.
    """
    logger = get_run_logger()
    logger.info("Starting CTAS pipeline...")
    run_ctas()
    logger.info("CTAS pipeline completed successfully.")

# Deployment configuration
DeploymentSpec(
    name="run_ctas_pipeline_deployment",
    flow=run_ctas_pipeline,
    schedule=CronSchedule(cron="0 0 * * *", timezone="UTC", catchup=False),
    work_pool_name="default-agent-pool",
    parameters={},
    tags=["data", "snowflake"],
    infra_overrides={"env": {"SNOWFLAKE_CONN": snowflake_conn.get(), "SLACK_CONN": slack_conn.get()}},
)
```
Note: Replace the placeholder comments with actual implementation details for the Snowflake connection and query execution.