# Generated by Airflow DAG generator on 2024-06-13
"""
DAG: RunELT_Alert
Description: Sequential ELT pipeline that builds analytics tables in Snowflake using CTAS
operations, with data validation, atomic swaps, and Slack failure notifications.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timedelta

import requests
from airflow import DAG
from airflow.decorators import task
from airflow.exceptions import AirflowException
from airflow.models import Variable
from airflow.providers.snowflake.hooks.snowflake import SnowflakeHook
from airflow.utils.trigger_rule import TriggerRule
from airflow.hooks.base import BaseHook

# Default arguments applied to all tasks unless overridden
default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": 0,
    "retry_delay": timedelta(minutes=5),
}

# -------------------------------------------------------------------------
# DAG definition
# -------------------------------------------------------------------------
with DAG(
    dag_id="RunELT_Alert",
    description="Sequential ELT pipeline that builds analytics tables in Snowflake using CTAS operations, with data validation, atomic swaps, and Slack failure notifications.",
    schedule_interval="@daily",
    start_date=datetime(2024, 1, 1),
    catchup=False,
    default_args=default_args,
    tags=["elt", "snowflake", "slack"],
    max_active_runs=1,
    timezone="UTC",
) as dag:

    # -----------------------------------------------------------------
    # Helper: Send message to Slack via webhook stored in a connection
    # -----------------------------------------------------------------
    def _post_to_slack(message: str) -> None:
        """
        Posts a JSON payload to a Slack webhook URL retrieved from the
        ``slack_conn`` Airflow connection (type ``http``).

        Args:
            message: Text message to send to Slack.
        """
        conn = BaseHook.get_connection("slack_conn")
        webhook_url = conn.host  # For HTTP connections Airflow stores the URL in ``host``
        if not webhook_url:
            raise AirflowException("Slack webhook URL not found in connection 'slack_conn'.")

        payload = {"text": message}
        headers = {"Content-Type": "application/json"}

        response = requests.post(webhook_url, data=json.dumps(payload), headers=headers, timeout=10)
        if response.status_code != 200:
            raise AirflowException(f"Failed to send Slack notification: {response.text}")

    # -----------------------------------------------------------------
    # Task: Run CTAS to Build Analytics Tables
    # -----------------------------------------------------------------
    @task(retries=0, retry_delay=timedelta(minutes=1))
    def run_ctas() -> None:
        """
        Executes CTAS (Create Table As Select) statements in Snowflake to build
        analytics tables. Raises AirflowException on any failure to trigger the
        failure notification downstream.
        """
        snowflake = SnowflakeHook(snowflake_conn_id="snowflake_conn")
        sql_statements = [
            """
            CREATE OR REPLACE TABLE analytics.sales_summary AS
            SELECT
                region,
                SUM(amount) AS total_sales,
                COUNT(*) AS transaction_count
            FROM raw.sales
            WHERE transaction_date >= DATEADD(day, -30, CURRENT_DATE())
            GROUP BY region;
            """,
            # Add additional CTAS statements as needed
        ]

        try:
            for sql in sql_statements:
                logging.info("Executing CTAS statement: %s", sql.strip())
                snowflake.run(sql)
            logging.info("All CTAS statements executed successfully.")
        except Exception as exc:
            logging.error("Error during CTAS execution: %s", exc)
            raise AirflowException(f"CTAS execution failed: {exc}")

    # -----------------------------------------------------------------
    # Task: Slack Failure Notification
    # -----------------------------------------------------------------
    @task(
        retries=3,
        retry_delay=timedelta(minutes=2),
        trigger_rule=TriggerRule.ONE_FAILED,
    )
    def notify_failure_slack(context: dict) -> None:
        """
        Sends a Slack notification when any upstream task fails.

        Args:
            context: Airflow context dictionary automatically passed when
                     ``provide_context=True`` (default for @task).
        """
        dag_run = context.get("dag_run")
        task_instance = context.get("task_instance")
        failed_task = context.get("task_instance").task_id if task_instance else "unknown"

        message = (
            f":x: *DAG Failed*: `{dag.dag_id}`\n"
            f"*Run*: `{dag_run.run_id if dag_run else 'N/A'}`\n"
            f"*Failed Task*: `{failed_task}`\n"
            f"*Execution Time*: `{datetime.utcnow().isoformat()} UTC`"
        )
        _post_to_slack(message)

    # -----------------------------------------------------------------
    # Define task pipeline
    # -----------------------------------------------------------------
    ctas_task = run_ctas()
    slack_task = notify_failure_slack()

    # Sequential execution with failure handling
    ctas_task >> slack_task