# Generated by Prefect 2.x Code Generator
# Date: 2023-10-04
# Prefect Version: 2.14.0

from prefect import flow, task, get_run_logger
from prefect_docker import DockerContainer
from prefect_docker.credentials import DockerHost
from prefect.blocks.system import Secret
from prefect.filesystems import LocalFileSystem
from prefect.task_runners import SequentialTaskRunner

# Load secrets and resources
data_dir = LocalFileSystem.load("data_dir")
load_and_modify_service = Secret.load("load_and_modify_service")
reconciliation_service = Secret.load("reconciliation_service")
save_service = Secret.load("save_service")
mongodb = Secret.load("mongodb")
intertwino_api = Secret.load("intertwino_api")

@task(retries=1, name="Load and Modify Data")
def load_and_modify_data():
    logger = get_run_logger()
    logger.info("Starting Load and Modify Data task")
    
    container = DockerContainer(
        image="i2t-backendwithintertwino6-load-and-modify:latest",
        env={
            "DATASET_ID": "2",
            "TABLE_NAME_PREFIX": "JOT_",
            "LOAD_AND_MODIFY_SERVICE": load_and_modify_service.get(),
            "MONGODB": mongodb.get(),
            "INTERTWINO_API": intertwino_api.get()
        },
        docker_host=DockerHost.load("docker_host"),
        stream_output=True
    )
    
    container.run()
    logger.info("Load and Modify Data task completed")

@task(retries=1, name="Entity Reconciliation")
def entity_reconciliation():
    logger = get_run_logger()
    logger.info("Starting Entity Reconciliation task")
    
    container = DockerContainer(
        image="i2t-backendwithintertwino6-reconciliation:latest",
        env={
            "PRIMARY_COLUMN": "supplier_name",
            "RECONCILIATOR_ID": "wikidataEntity",
            "DATASET_ID": "2",
            "RECONCILIATION_SERVICE": reconciliation_service.get(),
            "MONGODB": mongodb.get(),
            "INTERTWINO_API": intertwino_api.get()
        },
        docker_host=DockerHost.load("docker_host"),
        stream_output=True
    )
    
    container.run()
    logger.info("Entity Reconciliation task completed")

@task(retries=1, name="Save Final Data")
def save_final_data():
    logger = get_run_logger()
    logger.info("Starting Save Final Data task")
    
    container = DockerContainer(
        image="i2t-backendwithintertwino6-save:latest",
        env={
            "DATASET_ID": "2",
            "SAVE_SERVICE": save_service.get(),
            "MONGODB": mongodb.get(),
            "INTERTWINO_API": intertwino_api.get()
        },
        docker_host=DockerHost.load("docker_host"),
        stream_output=True
    )
    
    container.run()
    logger.info("Save Final Data task completed")

@flow(name="load_and_modify_data_pipeline", task_runner=SequentialTaskRunner())
def load_and_modify_data_pipeline():
    logger = get_run_logger()
    logger.info("Starting load_and_modify_data_pipeline")
    
    load_and_modify_data_result = load_and_modify_data()
    entity_reconciliation_result = entity_reconciliation(wait_for=[load_and_modify_data_result])
    save_final_data_result = save_final_data(wait_for=[entity_reconciliation_result])
    
    logger.info("load_and_modify_data_pipeline completed")

if __name__ == "__main__":
    load_and_modify_data_pipeline()