# Generated by Prefect 2.x Code Generator
# Date: [Current Date]
# Prefect Version: 2.14.0
# Flow Name: fetch_user_data_pipeline
# Deployment Name: fetch_user_data_pipeline_deployment
# Work Pool: default-agent-pool
# Task Runner: SequentialTaskRunner

from prefect import flow, task, get_run_logger
from prefect.tasks import task_input_hash
from prefect.blocks.system import Secret
from prefect.orion.schemas.schedules import CronSchedule
from prefect.deployments import DeploymentSpec
from prefect.flow_runners import SequentialTaskRunner
import requests
import psycopg2

# Load secrets
reqres_api = Secret.load("reqres_api").get()
postgres_db = Secret.load("postgres_db").get()

# Task: Fetch User Data
@task(retries=0, name="Fetch User Data")
def fetch_user_data():
    """
    Fetch user data from the Reqres API.
    """
    logger = get_run_logger()
    logger.info("Fetching user data from Reqres API...")
    response = requests.get(reqres_api)
    response.raise_for_status()
    return response.json()

# Task: Process User Data
@task(retries=0, name="Process User Data")
def process_user_data(user_data):
    """
    Process the fetched user data.
    """
    logger = get_run_logger()
    logger.info("Processing user data...")
    processed_data = []
    for user in user_data["data"]:
        processed_data.append({
            "id": user["id"],
            "first_name": user["first_name"],
            "last_name": user["last_name"],
            "email": user["email"]
        })
    return processed_data

# Task: Create User Table
@task(retries=0, name="Create User Table")
def create_user_table():
    """
    Create the user table in the PostgreSQL database.
    """
    logger = get_run_logger()
    logger.info("Creating user table in PostgreSQL database...")
    conn = psycopg2.connect(postgres_db)
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id SERIAL PRIMARY KEY,
            first_name VARCHAR(255),
            last_name VARCHAR(255),
            email VARCHAR(255) UNIQUE
        );
    """)
    conn.commit()
    cursor.close()
    conn.close()

# Task: Insert User Data
@task(retries=0, name="Insert User Data")
def insert_user_data(processed_data):
    """
    Insert the processed user data into the PostgreSQL database.
    """
    logger = get_run_logger()
    logger.info("Inserting user data into PostgreSQL database...")
    conn = psycopg2.connect(postgres_db)
    cursor = conn.cursor()
    for user in processed_data:
        cursor.execute("""
            INSERT INTO users (first_name, last_name, email)
            VALUES (%s, %s, %s)
            ON CONFLICT (email) DO NOTHING;
        """, (user["first_name"], user["last_name"], user["email"]))
    conn.commit()
    cursor.close()
    conn.close()

# Flow: fetch_user_data_pipeline
@flow(name="fetch_user_data_pipeline", task_runner=SequentialTaskRunner())
def fetch_user_data_pipeline():
    """
    Fetch user data from the Reqres API, process it, create a user table in PostgreSQL, and insert the data.
    """
    user_data = fetch_user_data()
    processed_data = process_user_data(user_data)
    create_user_table()
    insert_user_data(processed_data)

# Deployment Spec
DeploymentSpec(
    name="fetch_user_data_pipeline_deployment",
    flow=fetch_user_data_pipeline,
    schedule=CronSchedule(cron="0 0 * * *", timezone="UTC", catchup=False),
    work_pool_name="default-agent-pool",
    parameters={},
    tags=["data-ingestion", "api", "database"],
)