# Generated by Prefect 2.x Code Generator
# Date: 2023-10-05
# Prefect Version: 2.14.0

from prefect import flow, task, get_run_logger
from prefect.task_runners import SequentialTaskRunner
from prefect.blocks.system import Secret
from prefect.filesystems import LocalFileSystem
from prefect.infrastructure.docker import DockerContainer
from prefect.infrastructure.process import Process
from prefect.deployments import Deployment
from prefect.orion.schemas.schedules import CronSchedule
import pandas as pd
import os

# Load secrets and resources
postgres_default = Secret.load("postgres_default")
local_filesystem = LocalFileSystem.load("local_filesystem")
email_system = Secret.load("email_system")

@task(retries=2, name="Query Sales Data")
def query_sales_data():
    """
    Query sales data from the PostgreSQL database.
    """
    logger = get_run_logger()
    logger.info("Querying sales data from PostgreSQL database...")
    conn_str = postgres_default.get()
    query = "SELECT * FROM sales;"
    df = pd.read_sql(query, conn_str)
    logger.info("Sales data queried successfully.")
    return df

@task(retries=2, name="Transform to CSV")
def transform_to_csv(df):
    """
    Transform the queried sales data to a CSV file.
    """
    logger = get_run_logger()
    logger.info("Transforming sales data to CSV...")
    file_path = os.path.join(local_filesystem.basepath, "sales_data.csv")
    df.to_csv(file_path, index=False)
    logger.info(f"Sales data saved to {file_path}.")
    return file_path

@task(retries=2, name="Generate PDF Chart")
def generate_pdf_chart(csv_file_path):
    """
    Generate a PDF chart from the CSV file.
    """
    logger = get_run_logger()
    logger.info("Generating PDF chart from CSV file...")
    df = pd.read_csv(csv_file_path)
    # Example chart generation (replace with actual chart generation logic)
    chart_path = os.path.join(local_filesystem.basepath, "sales_chart.pdf")
    df.plot(kind='bar').get_figure().savefig(chart_path)
    logger.info(f"PDF chart saved to {chart_path}.")
    return chart_path

@task(retries=2, name="Email Sales Report")
def email_sales_report(pdf_file_path):
    """
    Email the sales report PDF.
    """
    logger = get_run_logger()
    logger.info("Emailing sales report PDF...")
    email_config = email_system.get()
    # Example email sending (replace with actual email sending logic)
    send_email(email_config, pdf_file_path)
    logger.info("Sales report PDF emailed successfully.")

def send_email(email_config, file_path):
    """
    Send an email with the sales report PDF attachment.
    """
    # Placeholder for actual email sending logic
    print(f"Sending email with attachment: {file_path}")

@flow(name="query_sales_data_pipeline", task_runner=SequentialTaskRunner())
def query_sales_data_pipeline():
    """
    Main flow for querying sales data, transforming it to CSV, generating a PDF chart, and emailing the report.
    """
    logger = get_run_logger()
    logger.info("Starting query_sales_data_pipeline...")

    # Query sales data
    sales_data = query_sales_data()

    # Transform to CSV
    csv_file_path = transform_to_csv(sales_data)

    # Generate PDF chart
    pdf_file_path = generate_pdf_chart(csv_file_path)

    # Email sales report
    email_sales_report(pdf_file_path)

    logger.info("query_sales_data_pipeline completed successfully.")

# Schedule the flow
deployment = Deployment.build_from_flow(
    flow=query_sales_data_pipeline,
    name="query_sales_data_pipeline_deployment",
    work_pool_name="default-agent-pool",
    schedule=CronSchedule(cron="0 0 * * *", timezone="UTC", catchup=False),
)

if __name__ == "__main__":
    deployment.apply()