# Generated by Prefect 2.x Code Generator
# Date: 2023-10-05
# Prefect Version: 2.14.0

from prefect import flow, task, get_run_logger
from prefect_docker import DockerContainer
from prefect_docker.containers import create_docker_container
from prefect.blocks.system import Secret
from prefect.filesystems import LocalFileSystem
from prefect.task_runners import SequentialTaskRunner

# Load secrets and resources
data_directory = LocalFileSystem.load("data_directory")
load_and_modify_service = Secret.load("load_and_modify_service")
reconciliation_service = Secret.load("reconciliation_service")
openmeteo_api = Secret.load("openmeteo_api")
column_extension_service = Secret.load("column_extension_service")
docker_network = Secret.load("docker_network")

@task(retries=1, name="Load and Modify Data")
def load_and_modify_data():
    logger = get_run_logger()
    logger.info("Starting Load and Modify Data task")
    container = create_docker_container(
        image="i2t-backendwithintertwino6-load-and-modify:latest",
        env={
            "DATASET_ID": "2",
            "DATE_COLUMN": "Fecha_id",
            "TABLE_NAMING_CONVENTION": "JOT_{}"
        },
        networks=[docker_network.get()],
        task_runner=SequentialTaskRunner()
    )
    return container

@task(retries=1, name="Data Reconciliation")
def data_reconciliation():
    logger = get_run_logger()
    logger.info("Starting Data Reconciliation task")
    container = create_docker_container(
        image="i2t-backendwithintertwino6-reconciliation:latest",
        env={
            "PRIMARY_COLUMN": "City",
            "OPTIONAL_COLUMNS": "County,Country",
            "RECONCILIATOR_ID": "geocodingHere",
            "API_TOKEN": reconciliation_service.get()
        },
        networks=[docker_network.get()],
        task_runner=SequentialTaskRunner()
    )
    return container

@task(retries=1, name="OpenMeteo Data Extension")
def openmeteo_data_extension():
    logger = get_run_logger()
    logger.info("Starting OpenMeteo Data Extension task")
    container = create_docker_container(
        image="i2t-backendwithintertwino6-openmeteo-extension:latest",
        env={
            "WEATHER_ATTRIBUTES": "apparent_temperature_max,apparent_temperature_min,precipitation_sum,precipitation_hours",
            "DATE_FORMAT": "your_date_format",
            "API_TOKEN": openmeteo_api.get()
        },
        networks=[docker_network.get()],
        task_runner=SequentialTaskRunner()
    )
    return container

@task(retries=1, name="Column Extension")
def column_extension():
    logger = get_run_logger()
    logger.info("Starting Column Extension task")
    container = create_docker_container(
        image="i2t-backendwithintertwino6-column-extension:latest",
        env={
            "EXTENDER_ID": "reconciledColumnExt"
        },
        networks=[docker_network.get()],
        task_runner=SequentialTaskRunner()
    )
    return container

@task(retries=1, name="Save Final Data")
def save_final_data():
    logger = get_run_logger()
    logger.info("Starting Save Final Data task")
    container = create_docker_container(
        image="i2t-backendwithintertwino6-save:latest",
        env={
            "DATA_DIR": "/app/data"
        },
        networks=[docker_network.get()],
        task_runner=SequentialTaskRunner()
    )
    return container

@flow(name="load_and_modify_data_pipeline", task_runner=SequentialTaskRunner())
def load_and_modify_data_pipeline():
    logger = get_run_logger()
    logger.info("Starting load_and_modify_data_pipeline")

    load_and_modify_data_result = load_and_modify_data()
    data_reconciliation_result = data_reconciliation(wait_for=[load_and_modify_data_result])
    openmeteo_data_extension_result = openmeteo_data_extension(wait_for=[data_reconciliation_result])
    column_extension_result = column_extension(wait_for=[openmeteo_data_extension_result])
    save_final_data_result = save_final_data(wait_for=[column_extension_result])

if __name__ == "__main__":
    load_and_modify_data_pipeline()