# Generated by Airflow DAG generator on 2024-06-28
"""
DAG: load_and_modify_data_pipeline
Description: Sequential pipeline that loads data, performs geocoding reconciliation,
extends data with weather, land use, and population density information, calculates
environmental risk, and saves the final dataset.
"""

from datetime import datetime, timedelta

from airflow import DAG
from airflow.providers.docker.operators.docker import DockerOperator
from airflow.utils.trigger_rule import TriggerRule
from airflow.utils.email import send_email
from airflow.utils.state import State


def failure_callback(context):
    """Send email on task failure."""
    dag_id = context.get("dag").dag_id
    task_id = context.get("task_instance").task_id
    execution_date = context.get("execution_date")
    log_url = context.get("task_instance").log_url

    subject = f"[Airflow] DAG {dag_id} - Task {task_id} Failed"
    html_content = f"""
    <p>Task <strong>{task_id}</strong> in DAG <strong>{dag_id}</strong> failed.</p>
    <p><strong>Execution date:</strong> {execution_date}</p>
    <p><strong>Log URL:</strong> <a href="{log_url}">{log_url}</a></p>
    """
    # Adjust the recipient list as needed
    send_email(to=["airflow-alerts@example.com"], subject=subject, html_content=html_content)


default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    "retries": 1,
    "retry_delay": timedelta(minutes=5),
    "on_failure_callback": failure_callback,
}

with DAG(
    dag_id="load_and_modify_data_pipeline",
    description="Sequential pipeline for loading, extending, and saving data.",
    default_args=default_args,
    schedule_interval=None,  # Disabled schedule
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["sequential", "docker"],
    max_active_runs=1,
) as dag:

    # -------------------------------------------------------------------------
    # Task: Load & Modify Data
    # -------------------------------------------------------------------------
    load_and_modify_data = DockerOperator(
        task_id="load_and_modify_data",
        image="i2t-backendwithintertwino6-load-and-modify:latest",
        api_version="auto",
        auto_remove=True,
        command=None,
        environment={
            "DATASET_ID": "2",
            "DATE_COLUMN": "installation_date",
            "TABLE_NAME_PREFIX": "JOT_",
            "DATA_DIR": "/data",
        },
        docker_url="unix://var/run/docker.sock",
        network_mode="app_network",
        mounts=[],
        tty=True,
        force_pull=True,
    )

    # -------------------------------------------------------------------------
    # Task: Geocoding Reconciliation
    # -------------------------------------------------------------------------
    geocode_reconciliation = DockerOperator(
        task_id="geocode_reconciliation",
        image="i2t-backendwithintertwino6-reconciliation:latest",
        api_version="auto",
        auto_remove=True,
        command=None,
        environment={
            "PRIMARY_COLUMN": "location",
            "RECONCILIATOR_ID": "geocodingHere",
            "API_TOKEN": "[HERE API token]",
            "DATASET_ID": "2",
            "DATA_DIR": "/data",
        },
        docker_url="unix://var/run/docker.sock",
        network_mode="app_network",
        mounts=[],
        tty=True,
        force_pull=True,
    )

    # -------------------------------------------------------------------------
    # Task: OpenMeteo Data Extension
    # -------------------------------------------------------------------------
    openmeteo_extension = DockerOperator(
        task_id="openmeteo_extension",
        image="i2t-backendwithintertwino6-openmeteo-extension:latest",
        api_version="auto",
        auto_remove=True,
        command=None,
        environment={
            "LAT_COLUMN": "latitude",
            "LON_COLUMN": "longitude",
            "DATE_COLUMN": "installation_date",
            "WEATHER_VARIABLES": "apparent_temperature_max,apparent_temperature_min,precipitation_sum,precipitation_hours",
            "DATE_SEPARATOR_FORMAT": "YYYYMMDD",
            "DATA_DIR": "/data",
        },
        docker_url="unix://var/run/docker.sock",
        network_mode="app_network",
        mounts=[],
        tty=True,
        force_pull=True,
    )

    # -------------------------------------------------------------------------
    # Task: Land Use Extension
    # -------------------------------------------------------------------------
    land_use_extension = DockerOperator(
        task_id="land_use_extension",
        image="geoapify-land-use:latest",
        api_version="auto",
        auto_remove=True,
        command=None,
        environment={
            "LAT_COLUMN": "latitude",
            "LON_COLUMN": "longitude",
            "OUTPUT_COLUMN": "land_use_type",
            "API_KEY": "[Geoapify API key]",
            "DATA_DIR": "/data",
        },
        docker_url="unix://var/run/docker.sock",
        network_mode="app_network",
        mounts=[],
        tty=True,
        force_pull=True,
    )

    # -------------------------------------------------------------------------
    # Task: Population Density Extension
    # -------------------------------------------------------------------------
    population_density_extension = DockerOperator(
        task_id="population_density_extension",
        image="worldpop-density:latest",
        api_version="auto",
        auto_remove=True,
        command=None,
        environment={
            "LAT_COLUMN": "latitude",
            "LON_COLUMN": "longitude",
            "OUTPUT_COLUMN": "population_density",
            "RADIUS": "5000",
            "DATA_DIR": "/data",
        },
        docker_url="unix://var/run/docker.sock",
        network_mode="app_network",
        mounts=[],
        tty=True,
        force_pull=True,
    )

    # -------------------------------------------------------------------------
    # Task: Environmental Calculation (Column Extension)
    # -------------------------------------------------------------------------
    calculate_environmental_risk = DockerOperator(
        task_id="calculate_environmental_risk",
        image="i2t-backendwithintertwino6-column-extension:latest",
        api_version="auto",
        auto_remove=True,
        command=None,
        environment={
            "EXTENDER_ID": "environmentalRiskCalculator",
            "INPUT_COLUMNS": "precipitation_sum,population_density,land_use_type",
            "OUTPUT_COLUMN": "risk_score",
            "CALCULATION_FORMULA": "[risk calculation parameters]",
            "DATA_DIR": "/data",
        },
        docker_url="unix://var/run/docker.sock",
        network_mode="app_network",
        mounts=[],
        tty=True,
        force_pull=True,
    )

    # -------------------------------------------------------------------------
    # Task: Save Final Data
    # -------------------------------------------------------------------------
    save_final_data = DockerOperator(
        task_id="save_final_data",
        image="i2t-backendwithintertwino6-save:latest",
        api_version="auto",
        auto_remove=True,
        command=None,
        environment={
            "DATASET_ID": "2",
            "DATA_DIR": "/data",
        },
        docker_url="unix://var/run/docker.sock",
        network_mode="app_network",
        mounts=[],
        tty=True,
        force_pull=True,
    )

    # -------------------------------------------------------------------------
    # Set task dependencies (sequential flow)
    # -------------------------------------------------------------------------
    load_and_modify_data >> geocode_reconciliation >> openmeteo_extension \
        >> land_use_extension >> population_density_extension \
        >> calculate_environmental_risk >> save_final_data