# Generated by Prefect 2.x Code Generator
# Date: 2023-10-05
# Prefect Version: 2.14.0

from prefect import flow, task, get_run_logger
from prefect.task_runners import ConcurrentTaskRunner
from prefect.deployments import Deployment
from prefect.infrastructure import DockerContainer, Process
from prefect.filesystems import LocalFileSystem
from prefect.blocks.system import Secret
from prefect import flow, task
from prefect.tasks import task_input_hash
from datetime import timedelta
import os

# Load connections/resources
local_filesystem = LocalFileSystem.load("local_filesystem")
email_delivery_system = Secret.load("email_delivery_system")
sms_gateway = Secret.load("sms_gateway")
push_notification_service = Secret.load("push_notification_service")

@task(retries=2, retry_delay_seconds=10)
def load_customer_segment_csv():
    """
    Load customer segment CSV from the local file system.
    """
    logger = get_run_logger()
    file_path = os.path.join(local_filesystem.basepath, "customer_segment.csv")
    logger.info(f"Loading customer segment CSV from {file_path}")
    # Simulate loading CSV
    with open(file_path, "r") as file:
        data = file.read()
    logger.info("Customer segment CSV loaded successfully")
    return data

@task(retries=2, retry_delay_seconds=10)
def send_email_campaign(data):
    """
    Send email campaign using the email delivery system.
    """
    logger = get_run_logger()
    logger.info("Sending email campaign")
    # Simulate sending email campaign
    email_delivery_system_value = email_delivery_system.get()
    logger.info(f"Email delivery system: {email_delivery_system_value}")
    logger.info("Email campaign sent successfully")

@task(retries=2, retry_delay_seconds=10)
def send_push_notification(data):
    """
    Send push notification using the push notification service.
    """
    logger = get_run_logger()
    logger.info("Sending push notification")
    # Simulate sending push notification
    push_notification_service_value = push_notification_service.get()
    logger.info(f"Push notification service: {push_notification_service_value}")
    logger.info("Push notification sent successfully")

@task(retries=2, retry_delay_seconds=10)
def send_sms_campaign(data):
    """
    Send SMS campaign using the SMS gateway.
    """
    logger = get_run_logger()
    logger.info("Sending SMS campaign")
    # Simulate sending SMS campaign
    sms_gateway_value = sms_gateway.get()
    logger.info(f"SMS gateway: {sms_gateway_value}")
    logger.info("SMS campaign sent successfully")

@flow(name="load_customer_segment_csv_pipeline", task_runner=ConcurrentTaskRunner())
def load_customer_segment_csv_pipeline():
    """
    Load customer segment CSV and send email, push notification, and SMS campaigns.
    """
    logger = get_run_logger()
    logger.info("Starting load_customer_segment_csv_pipeline")

    # Load customer segment CSV
    data = load_customer_segment_csv()

    # Send email, push notification, and SMS campaigns
    send_email_campaign(data)
    send_push_notification(data)
    send_sms_campaign(data)

# Schedule configuration
deployment = Deployment.build_from_flow(
    flow=load_customer_segment_csv_pipeline,
    name="load_customer_segment_csv_pipeline_deployment",
    work_pool_name="default-agent-pool",
    schedule=(None, "0 0 * * *", "UTC", False),
)

if __name__ == "__main__":
    deployment.apply()