# Generated by Dagster Code Generator
# Date: 2023-10-04
# Dagster Version: 1.5.0

from dagster import (
    job,
    op,
    In,
    Out,
    RetryPolicy,
    ResourceDefinition,
    fs_io_manager,
    multiprocess_executor,
    ScheduleDefinition,
    DefaultScheduleStatus,
)

# Resources
north_warehouse_api = ResourceDefinition.mock_resource()
south_warehouse_api = ResourceDefinition.mock_resource()
east_warehouse_api = ResourceDefinition.mock_resource()
west_warehouse_api = ResourceDefinition.mock_resource()
xcom_storage = ResourceDefinition.mock_resource()

# Ops
@op(
    required_resource_keys={"east_warehouse_api"},
    out={"east_csv": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def fetch_east_warehouse_csv(context):
    """Fetch CSV data from the East Warehouse Management System."""
    east_csv = context.resources.east_warehouse_api.fetch_csv()
    return east_csv

@op(
    required_resource_keys={"north_warehouse_api"},
    out={"north_csv": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def fetch_north_warehouse_csv(context):
    """Fetch CSV data from the North Warehouse Management System."""
    north_csv = context.resources.north_warehouse_api.fetch_csv()
    return north_csv

@op(
    required_resource_keys={"south_warehouse_api"},
    out={"south_csv": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def fetch_south_warehouse_csv(context):
    """Fetch CSV data from the South Warehouse Management System."""
    south_csv = context.resources.south_warehouse_api.fetch_csv()
    return south_csv

@op(
    required_resource_keys={"west_warehouse_api"},
    out={"west_csv": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def fetch_west_warehouse_csv(context):
    """Fetch CSV data from the West Warehouse Management System."""
    west_csv = context.resources.west_warehouse_api.fetch_csv()
    return west_csv

@op(
    ins={"east_csv": In()},
    out={"normalized_east_skus": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def normalize_east_skus(context, east_csv):
    """Normalize SKUs from the East Warehouse CSV."""
    normalized_east_skus = east_csv  # Placeholder for actual normalization logic
    return normalized_east_skus

@op(
    ins={"north_csv": In()},
    out={"normalized_north_skus": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def normalize_north_skus(context, north_csv):
    """Normalize SKUs from the North Warehouse CSV."""
    normalized_north_skus = north_csv  # Placeholder for actual normalization logic
    return normalized_north_skus

@op(
    ins={"south_csv": In()},
    out={"normalized_south_skus": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def normalize_south_skus(context, south_csv):
    """Normalize SKUs from the South Warehouse CSV."""
    normalized_south_skus = south_csv  # Placeholder for actual normalization logic
    return normalized_south_skus

@op(
    ins={"west_csv": In()},
    out={"normalized_west_skus": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def normalize_west_skus(context, west_csv):
    """Normalize SKUs from the West Warehouse CSV."""
    normalized_west_skus = west_csv  # Placeholder for actual normalization logic
    return normalized_west_skus

@op(
    ins={
        "normalized_north_skus": In(),
        "normalized_south_skus": In(),
        "normalized_east_skus": In(),
        "normalized_west_skus": In(),
    },
    out={"reconciled_inventories": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def reconcile_all_inventories(
    context,
    normalized_north_skus,
    normalized_south_skus,
    normalized_east_skus,
    normalized_west_skus,
):
    """Reconcile inventories from all normalized SKUs."""
    reconciled_inventories = {
        "north": normalized_north_skus,
        "south": normalized_south_skus,
        "east": normalized_east_skus,
        "west": normalized_west_skus,
    }
    return reconciled_inventories

@op(
    ins={"reconciled_inventories": In()},
    out={"final_report": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def generate_final_report(context, reconciled_inventories):
    """Generate the final report from the reconciled inventories."""
    final_report = reconciled_inventories  # Placeholder for actual report generation logic
    return final_report

# Job
@job(
    name="fetch_north_warehouse_csv_pipeline",
    description="No description provided.",
    executor_def=multiprocess_executor,
    resource_defs={
        "north_warehouse_api": north_warehouse_api,
        "south_warehouse_api": south_warehouse_api,
        "east_warehouse_api": east_warehouse_api,
        "west_warehouse_api": west_warehouse_api,
        "xcom_storage": xcom_storage,
        "io_manager": fs_io_manager,
    },
)
def fetch_north_warehouse_csv_pipeline():
    north_csv = fetch_north_warehouse_csv()
    south_csv = fetch_south_warehouse_csv()
    east_csv = fetch_east_warehouse_csv()
    west_csv = fetch_west_warehouse_csv()

    normalized_north_skus = normalize_north_skus(north_csv)
    normalized_south_skus = normalize_south_skus(south_csv)
    normalized_east_skus = normalize_east_skus(east_csv)
    normalized_west_skus = normalize_west_skus(west_csv)

    reconciled_inventories = reconcile_all_inventories(
        normalized_north_skus,
        normalized_south_skus,
        normalized_east_skus,
        normalized_west_skus,
    )

    generate_final_report(reconciled_inventories)

# Schedule
fetch_north_warehouse_csv_pipeline_schedule = ScheduleDefinition(
    job=fetch_north_warehouse_csv_pipeline,
    cron_schedule="@daily",
    execution_timezone="UTC",
    name="fetch_north_warehouse_csv_pipeline_schedule",
    default_status=DefaultScheduleStatus.RUNNING,
    should_execute=lambda _context: True,
)