# Generated by Dagster Code Generator
# Generation Metadata:
# - Job Name: fetch_brokerage_holdings_pipeline
# - Description: No description provided.
# - Executor Type: multiprocess_executor
# - IO Manager: fs_io_manager
# - Dagster Version: 1.5.0
# - Use Assets: False
# - Required Resources: mock_brokerage_api

from dagster import (
    job,
    op,
    Out,
    In,
    RetryPolicy,
    multiprocess_executor,
    fs_io_manager,
    resource,
)

@resource
def mock_brokerage_api():
    """Mock Brokerage API resource."""
    pass

@op(
    name="fetch_brokerage_holdings",
    out={"holdings": Out()},
    retry_policy=RetryPolicy(max_retries=2),
    required_resource_keys={"mock_brokerage_api"},
)
def fetch_brokerage_holdings(context):
    """Fetch holdings from the mock brokerage API."""
    # Simulate fetching data from the mock brokerage API
    holdings = {"data": "mock_holdings_data"}
    context.log.info(f"Fetched holdings: {holdings}")
    return holdings

@op(
    name="analyze_portfolio",
    ins={"holdings": In()},
    out={"portfolio_analysis": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def analyze_portfolio(context, holdings):
    """Analyze the portfolio based on the fetched holdings."""
    # Simulate portfolio analysis
    portfolio_analysis = {"analysis": "mock_analysis_data"}
    context.log.info(f"Analyzed portfolio: {portfolio_analysis}")
    return portfolio_analysis

@op(
    name="aggregate_and_rebalance",
    ins={"portfolio_analysis": In()},
    out={"rebalanced_portfolio": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def aggregate_and_rebalance(context, portfolio_analysis):
    """Aggregate and rebalance the portfolio based on the analysis."""
    # Simulate aggregation and rebalancing
    rebalanced_portfolio = {"rebalanced": "mock_rebalanced_data"}
    context.log.info(f"Rebalanced portfolio: {rebalanced_portfolio}")
    return rebalanced_portfolio

@op(
    name="generate_trade_orders",
    ins={"rebalanced_portfolio": In()},
    out={"trade_orders": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def generate_trade_orders(context, rebalanced_portfolio):
    """Generate trade orders based on the rebalanced portfolio."""
    # Simulate generating trade orders
    trade_orders = {"orders": "mock_trade_orders"}
    context.log.info(f"Generated trade orders: {trade_orders}")
    return trade_orders

@job(
    name="fetch_brokerage_holdings_pipeline",
    description="No description provided.",
    executor_def=multiprocess_executor,
    resource_defs={"mock_brokerage_api": mock_brokerage_api, "io_manager": fs_io_manager},
)
def fetch_brokerage_holdings_pipeline():
    """Dagster job to fetch brokerage holdings, analyze the portfolio, aggregate and rebalance, and generate trade orders."""
    # Fan out fetch_brokerage_holdings
    holdings_1 = fetch_brokerage_holdings.alias("fetch_brokerage_holdings_1")()
    holdings_2 = fetch_brokerage_holdings.alias("fetch_brokerage_holdings_2")()
    holdings_3 = fetch_brokerage_holdings.alias("fetch_brokerage_holdings_3")()
    holdings_4 = fetch_brokerage_holdings.alias("fetch_brokerage_holdings_4")()
    holdings_5 = fetch_brokerage_holdings.alias("fetch_brokerage_holdings_5")()

    # Fan in analyze_portfolio
    portfolio_analysis_1 = analyze_portfolio(holdings_1)
    portfolio_analysis_2 = analyze_portfolio(holdings_2)
    portfolio_analysis_3 = analyze_portfolio(holdings_3)
    portfolio_analysis_4 = analyze_portfolio(holdings_4)
    portfolio_analysis_5 = analyze_portfolio(holdings_5)

    # Fan in aggregate_and_rebalance
    rebalanced_portfolio_1 = aggregate_and_rebalance(portfolio_analysis_1)
    rebalanced_portfolio_2 = aggregate_and_rebalance(portfolio_analysis_2)
    rebalanced_portfolio_3 = aggregate_and_rebalance(portfolio_analysis_3)
    rebalanced_portfolio_4 = aggregate_and_rebalance(portfolio_analysis_4)
    rebalanced_portfolio_5 = aggregate_and_rebalance(portfolio_analysis_5)

    # Fan in generate_trade_orders
    generate_trade_orders(rebalanced_portfolio_1, rebalanced_portfolio_2, rebalanced_portfolio_3, rebalanced_portfolio_4, rebalanced_portfolio_5)