# Generated by Airflow DAG generator on 2024-06-28
# DAG: load_modify_facilities_pipeline
# Description: Sequential pipeline to load, modify, enrich and save facilities data.

import os
from datetime import timedelta

from airflow import DAG
from airflow.utils.dates import days_ago
from airflow.providers.docker.operators.docker import DockerOperator
from airflow.utils.trigger_rule import TriggerRule
from airflow.models import Variable
from airflow.utils.email import send_email

# -------------------------------------------------------------------------
# Default arguments applied to all tasks
# -------------------------------------------------------------------------
default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    "retries": 1,
    "retry_delay": timedelta(minutes=5),
    "email_on_failure": False,
    "email_on_retry": False,
}


def failure_callback(context):
    """Send an email when a task fails."""
    dag_id = context.get("dag").dag_id
    task_id = context.get("task_instance").task_id
    execution_date = context.get("execution_date")
    log_url = context.get("task_instance").log_url

    subject = f"[Airflow] DAG {dag_id} - Task {task_id} Failed"
    html_content = f"""
    <p>Task <strong>{task_id}</strong> in DAG <strong>{dag_id}</strong> failed.</p>
    <p>Execution date: {execution_date}</p>
    <p>Log URL: <a href="{log_url}">{log_url}</a></p>
    """
    # Adjust the recipient list as needed
    send_email(to=["airflow-alerts@example.com"], subject=subject, html_content=html_content)


# -------------------------------------------------------------------------
# DAG definition
# -------------------------------------------------------------------------
with DAG(
    dag_id="load_modify_facilities_pipeline",
    description="Sequential pipeline to load, modify, enrich and save facilities data.",
    schedule_interval=None,  # Disabled schedule
    start_date=days_ago(1),
    catchup=False,
    default_args=default_args,
    tags=["load_modify", "facilities"],
    on_failure_callback=failure_callback,
) as dag:

    # ---------------------------------------------------------------------
    # Shared volume configuration
    # ---------------------------------------------------------------------
    # The shared DATA_DIR volume is expected to be mounted on the host.
    # Its path can be overridden via an Airflow Variable named `data_dir_volume`.
    DATA_DIR_HOST_PATH = Variable.get("data_dir_volume", default_var="/mnt/data_dir")
    DATA_DIR_CONTAINER_PATH = "/app/data"

    # ---------------------------------------------------------------------
    # Task: Load and Modify Facilities Data
    # ---------------------------------------------------------------------
    load_modify_facilities = DockerOperator(
        task_id="load_modify_facilities",
        image="i2t-backendwithintertwino6-load-and-modify:latest",
        api_version="auto",
        auto_remove=True,
        docker_url="unix://var/run/docker.sock",
        network_mode="bridge",
        environment={
            "DATASET_ID": "2",
            "TABLE_NAME_PREFIX": "JOT_",
        },
        volumes=[f"{DATA_DIR_HOST_PATH}:{DATA_DIR_CONTAINER_PATH}"],
        command=None,
        trigger_rule=TriggerRule.ALL_SUCCESS,
    )

    # ---------------------------------------------------------------------
    # Task: Geocode Facilities Using HERE API
    # ---------------------------------------------------------------------
    # HERE API token is stored as an Airflow Variable `here_api_token`.
    HERE_API_TOKEN = Variable.get("here_api_token", default_var="YOUR_HERE_API_TOKEN")
    geocode_facilities = DockerOperator(
        task_id="geocode_facilities",
        image="i2t-backendwithintertwino6-reconciliation:latest",
        api_version="auto",
        auto_remove=True,
        docker_url="unix://var/run/docker.sock",
        network_mode="bridge",
        environment={
            "PRIMARY_COLUMN": "address",
            "RECONCILIATOR_ID": "geocodingHere",
            "API_TOKEN": HERE_API_TOKEN,
            "DATASET_ID": "2",
        },
        volumes=[f"{DATA_DIR_HOST_PATH}:{DATA_DIR_CONTAINER_PATH}"],
        command=None,
        trigger_rule=TriggerRule.ALL_SUCCESS,
    )

    # ---------------------------------------------------------------------
    # Task: Calculate Distance to Nearest Public Transport
    # ---------------------------------------------------------------------
    calculate_distance_to_public_transport = DockerOperator(
        task_id="calculate_distance_to_public_transport",
        image="i2t-backendwithintertwino6-column-extension:latest",
        api_version="auto",
        auto_remove=True,
        docker_url="unix://var/run/docker.sock",
        network_mode="bridge",
        environment={
            "EXTENDER_ID": "spatialDistanceCalculator",
            "LAT_COLUMN": "latitude",
            "LON_COLUMN": "longitude",
            "TARGET_LAYER": "public_transport",
            "TARGET_DATA_SOURCE": f"{DATA_DIR_CONTAINER_PATH}/transport_stops.geojson",
            "OUTPUT_COLUMN": "distance_to_pt",
            "DATASET_ID": "2",
        },
        volumes=[f"{DATA_DIR_HOST_PATH}:{DATA_DIR_CONTAINER_PATH}"],
        command=None,
        trigger_rule=TriggerRule.ALL_SUCCESS,
    )

    # ---------------------------------------------------------------------
    # Task: Calculate Distance to Nearest Residential Area
    # ---------------------------------------------------------------------
    calculate_distance_to_residential_areas = DockerOperator(
        task_id="calculate_distance_to_residential_areas",
        image="i2t-backendwithintertwino6-column-extension:latest",
        api_version="auto",
        auto_remove=True,
        docker_url="unix://var/run/docker.sock",
        network_mode="bridge",
        environment={
            "EXTENDER_ID": "spatialDistanceCalculator",
            "LAT_COLUMN": "latitude",
            "LON_COLUMN": "longitude",
            "TARGET_LAYER": "residential_areas",
            "TARGET_DATA_SOURCE": f"{DATA_DIR_CONTAINER_PATH}/residential_areas.geojson",
            "OUTPUT_COLUMN": "distance_to_residential",
            "DATASET_ID": "2",
        },
        volumes=[f"{DATA_DIR_HOST_PATH}:{DATA_DIR_CONTAINER_PATH}"],
        command=None,
        trigger_rule=TriggerRule.ALL_SUCCESS,
    )

    # ---------------------------------------------------------------------
    # Task: Save Enriched Facility Accessibility Data
    # ---------------------------------------------------------------------
    save_facilities_accessibility = DockerOperator(
        task_id="save_facilities_accessibility",
        image="i2t-backendwithintertwino6-save:latest",
        api_version="auto",
        auto_remove=True,
        docker_url="unix://var/run/docker.sock",
        network_mode="bridge",
        environment={
            "DATASET_ID": "2",
        },
        volumes=[f"{DATA_DIR_HOST_PATH}:{DATA_DIR_CONTAINER_PATH}"],
        command=None,
        trigger_rule=TriggerRule.ALL_SUCCESS,
    )

    # ---------------------------------------------------------------------
    # Set task dependencies (sequential execution)
    # ---------------------------------------------------------------------
    load_modify_facilities >> geocode_facilities >> calculate_distance_to_public_transport \
        >> calculate_distance_to_residential_areas >> save_facilities_accessibility