# Generated by Prefect 2.x Code Generator
# Date: 2023-10-05
# Prefect Version: 2.14.0

from prefect import flow, task, get_run_logger
from prefect.task_runners import SequentialTaskRunner
from prefect.blocks.system import Secret, LocalFileSystem
from prefect.infrastructure import DockerContainer, Process
from prefect_email import EmailServerCredentials, email_send_message
import json
import psycopg2

# Load secrets and resources
mahidol_aqi_website = Secret.load("mahidol_aqi_website")
local_filesystem = LocalFileSystem.load("local_filesystem")
postgres_conn = Secret.load("postgres_conn")
smtp_server = Secret.load("smtp_server")
config_filesystem = LocalFileSystem.load("config_filesystem")

@task(retries=0, name="Get Mahidol AQI Report")
def get_data_mahidol_aqi_report():
    """
    Fetches the AQI report from the Mahidol University website.
    """
    logger = get_run_logger()
    url = mahidol_aqi_website.get()
    logger.info(f"Fetching data from {url}")
    # Simulate data fetching
    data = {"aqi": 50, "location": "Bangkok", "timestamp": "2023-10-05T12:00:00Z"}
    return data

@task(retries=0, name="Create JSON Object")
def create_json_object(data):
    """
    Creates a JSON object from the fetched AQI report.
    """
    logger = get_run_logger()
    logger.info("Creating JSON object")
    json_data = json.dumps(data)
    return json_data

@task(retries=0, name="Load Mahidol AQI to PostgreSQL")
def load_mahidol_aqi_to_postgres(json_data):
    """
    Loads the JSON object into a PostgreSQL database.
    """
    logger = get_run_logger()
    logger.info("Loading data into PostgreSQL")
    conn_info = postgres_conn.get()
    conn = psycopg2.connect(**conn_info)
    cursor = conn.cursor()
    cursor.execute("INSERT INTO aqi_reports (data) VALUES (%s)", (json_data,))
    conn.commit()
    cursor.close()
    conn.close()

@task(retries=0, name="Send Email Alert")
def alert_email():
    """
    Sends an email alert after the data has been loaded into PostgreSQL.
    """
    logger = get_run_logger()
    logger.info("Sending email alert")
    smtp_info = smtp_server.get()
    email_credentials = EmailServerCredentials(
        username=smtp_info["username"],
        password=smtp_info["password"],
        smtp_server=smtp_info["server"],
        smtp_port=smtp_info["port"],
    )
    email_send_message(
        email_server_credentials=email_credentials,
        subject="Mahidol AQI Report Loaded",
        msg="The Mahidol AQI report has been successfully loaded into PostgreSQL.",
        email_to="recipient@example.com",
    )

@flow(name="get_data_mahidol_aqi_report_pipeline", task_runner=SequentialTaskRunner())
def get_data_mahidol_aqi_report_pipeline():
    """
    Main flow for fetching, processing, and loading the Mahidol AQI report.
    """
    logger = get_run_logger()
    logger.info("Starting Mahidol AQI Report Pipeline")

    data = get_data_mahidol_aqi_report()
    json_data = create_json_object(data)
    load_mahidol_aqi_to_postgres(json_data)
    alert_email()

if __name__ == "__main__":
    get_data_mahidol_aqi_report_pipeline()