# Generated by Dagster Code Generator
# Generation Metadata:
# - Job Name: ingest_vendor_a_pipeline
# - Description: No description provided.
# - Executor Type: multiprocess_executor
# - IO Manager: fs_io_manager
# - Dagster Version: 1.5.0
# - Use Assets: False
# - Required Resources: inventory_db, vendor_c_filesystem, email_system, location_reference_tables, vendor_b_filesystem, vendor_a_filesystem

from dagster import (
    job,
    op,
    Out,
    In,
    RetryPolicy,
    multiprocess_executor,
    fs_io_manager,
    resource,
    schedule,
)

# Resources
@resource
def vendor_a_data_source():
    """Vendor A Data Source"""
    pass

@resource
def vendor_b_data_source():
    """Vendor B Data Source"""
    pass

@resource
def vendor_c_data_source():
    """Vendor C Data Source"""
    pass

@resource
def location_reference_tables():
    """Location Reference Tables"""
    pass

@resource
def inventory_database():
    """Inventory Database"""
    pass

@resource
def email_system():
    """Email System"""
    pass

# Ops
@op(
    required_resource_keys={"vendor_a_data_source"},
    out={"vendor_a_data": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def ingest_vendor_a(context):
    """Ingest Vendor A Data"""
    vendor_a_data = context.resources.vendor_a_data_source.load_data()
    return vendor_a_data

@op(
    required_resource_keys={"vendor_b_data_source"},
    out={"vendor_b_data": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def ingest_vendor_b(context):
    """Ingest Vendor B Data"""
    vendor_b_data = context.resources.vendor_b_data_source.load_data()
    return vendor_b_data

@op(
    required_resource_keys={"vendor_c_data_source"},
    out={"vendor_c_data": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def ingest_vendor_c(context):
    """Ingest Vendor C Data"""
    vendor_c_data = context.resources.vendor_c_data_source.load_data()
    return vendor_c_data

@op(
    ins={
        "vendor_a_data": In(),
        "vendor_b_data": In(),
        "vendor_c_data": In(),
    },
    out={"cleaned_data": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def cleanse_data(context, vendor_a_data, vendor_b_data, vendor_c_data):
    """Cleanse and Normalize Data"""
    cleaned_data = {
        "vendor_a": vendor_a_data,
        "vendor_b": vendor_b_data,
        "vendor_c": vendor_c_data,
    }
    return cleaned_data

@op(
    required_resource_keys={"inventory_database"},
    ins={"cleaned_data": In()},
    out={"db_load_status": Out()},
    retry_policy=RetryPolicy(max_retries=2),
)
def load_to_db(context, cleaned_data):
    """Load to Database"""
    db_load_status = context.resources.inventory_database.load_data(cleaned_data)
    return db_load_status

@op(
    required_resource_keys={"email_system"},
    ins={"db_load_status": In()},
    retry_policy=RetryPolicy(max_retries=2),
)
def send_summary_email(context, db_load_status):
    """Send Summary Email"""
    context.resources.email_system.send_email(db_load_status)

# Job
@job(
    name="ingest_vendor_a_pipeline",
    description="No description provided.",
    executor_def=multiprocess_executor,
    resource_defs={
        "vendor_a_data_source": vendor_a_data_source,
        "vendor_b_data_source": vendor_b_data_source,
        "vendor_c_data_source": vendor_c_data_source,
        "location_reference_tables": location_reference_tables,
        "inventory_database": inventory_database,
        "email_system": email_system,
        "io_manager": fs_io_manager,
    },
)
def ingest_vendor_a_pipeline():
    vendor_a_data = ingest_vendor_a()
    vendor_b_data = ingest_vendor_b()
    vendor_c_data = ingest_vendor_c()
    cleaned_data = cleanse_data(vendor_a_data, vendor_b_data, vendor_c_data)
    db_load_status = load_to_db(cleaned_data)
    send_summary_email(db_load_status)

# Schedule
@schedule(
    job=ingest_vendor_a_pipeline,
    cron_schedule="@daily",
    execution_timezone="UTC",
    name="ingest_vendor_a_pipeline_schedule",
    should_execute=lambda: True,
    execution_time=datetime.time(hour=0, minute=0),
    tags={"dagster/priority": "1"},
)
def ingest_vendor_a_pipeline_schedule(context):
    return {}