# Generated by Airflow DAG generator on 2024-06-13 12:00:00 UTC
"""
DAG: dump_prod_csv_pipeline
Description: No description provided.
Pattern: fanout
"""

from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.bash import BashOperator
from airflow.utils.trigger_rule import TriggerRule
from airflow.utils.email import send_email

# ----------------------------------------------------------------------
# Default arguments applied to all tasks
# ----------------------------------------------------------------------
default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    "retries": 2,
    "retry_delay": timedelta(minutes=5),
    "email_on_failure": False,
    "email_on_retry": False,
}


def failure_callback(context):
    """Send a simple email on task failure (optional)."""
    dag_id = context.get("dag").dag_id
    task_id = context.get("task_instance").task_id
    execution_date = context.get("execution_date")
    log_url = context.get("task_instance").log_url

    subject = f"[Airflow] Task Failed: {dag_id}.{task_id}"
    html_content = f"""
    <p>Task <strong>{task_id}</strong> in DAG <strong>{dag_id}</strong> failed.</p>
    <p>Execution date: {execution_date}</p>
    <p>Log URL: <a href="{log_url}">{log_url}</a></p>
    """
    # Adjust the recipient list as needed
    send_email(to=["airflow-alerts@example.com"], subject=subject, html_content=html_content)


# ----------------------------------------------------------------------
# DAG definition
# ----------------------------------------------------------------------
with DAG(
    dag_id="dump_prod_csv_pipeline",
    description="No description provided.",
    schedule_interval="@daily",
    start_date=datetime(2024, 1, 1),
    catchup=False,
    default_args=default_args,
    tags=["fanout"],
    max_active_runs=1,
    is_paused_upon_creation=True,  # Disabled by default
    timezone="UTC",
) as dag:

    # ------------------------------------------------------------------
    # Task: Dump Production Database to CSV
    # ------------------------------------------------------------------
    dump_prod_csv = BashOperator(
        task_id="dump_prod_csv",
        bash_command=(
            "echo 'Dumping production DB to CSV...'; "
            "# Replace the line below with the actual dump command, e.g.: "
            "# pg_dump -h {{ conn.prod_db.host }} -U {{ conn.prod_db.login }} ... > /tmp/prod_dump.csv"
        ),
        on_failure_callback=failure_callback,
        retries=2,
        retry_delay=timedelta(minutes=5),
    )

    # ------------------------------------------------------------------
    # Task: Load CSV Snapshot into Development Database
    # ------------------------------------------------------------------
    copy_dev = BashOperator(
        task_id="copy_dev",
        bash_command=(
            "echo 'Loading CSV into Development DB...'; "
            "# Replace with actual load command, e.g.: "
            "# psql -h {{ conn.dev_db.host }} -U {{ conn.dev_db.login }} -c \"\\copy table FROM '/tmp/prod_dump.csv' CSV\""
        ),
        on_failure_callback=failure_callback,
        retries=2,
        retry_delay=timedelta(minutes=5),
    )

    # ------------------------------------------------------------------
    # Task: Load CSV Snapshot into QA Database
    # ------------------------------------------------------------------
    copy_qa = BashOperator(
        task_id="copy_qa",
        bash_command=(
            "echo 'Loading CSV into QA DB...'; "
            "# Replace with actual load command, e.g.: "
            "# psql -h {{ conn.qa_db.host }} -U {{ conn.qa_db.login }} -c \"\\copy table FROM '/tmp/prod_dump.csv' CSV\""
        ),
        on_failure_callback=failure_callback,
        retries=2,
        retry_delay=timedelta(minutes=5),
    )

    # ------------------------------------------------------------------
    # Task: Load CSV Snapshot into Staging Database
    # ------------------------------------------------------------------
    copy_staging = BashOperator(
        task_id="copy_staging",
        bash_command=(
            "echo 'Loading CSV into Staging DB...'; "
            "# Replace with actual load command, e.g.: "
            "# psql -h {{ conn.staging_db.host }} -U {{ conn.staging_db.login }} -c \"\\copy table FROM '/tmp/prod_dump.csv' CSV\""
        ),
        on_failure_callback=failure_callback,
        retries=2,
        retry_delay=timedelta(minutes=5),
    )

    # ------------------------------------------------------------------
    # Set task dependencies (fanout pattern)
    # ------------------------------------------------------------------
    dump_prod_csv >> [copy_dev, copy_qa, copy_staging]