# Generated by Dagster Code Generator
# Generation Metadata:
# - Job Name: run_system_check_pipeline
# - Description: No description provided.
# - Executor Type: in_process_executor
# - IO Manager: fs_io_manager
# - Dagster Version: 1.5.0
# - Use Assets: False
# - Required Resources: hive_local

from dagster import job, op, In, Out, RetryPolicy, fs_io_manager, in_process_executor, resource

@resource
def hive_local():
    """Resource for connecting to the Hive Local Database."""
    # Implementation for connecting to Hive Local Database
    pass

@op(
    name="run_system_check",
    description="Run System Check",
    out=Out(str, description="Output of the system check"),
    retry_policy=RetryPolicy(max_retries=0),
)
def run_system_check(context):
    """Run a system check using the local shell."""
    # Example command to run a system check
    result = context.resources.local_shell.run("systemctl status")
    return result.stdout.decode("utf-8")

@op(
    name="execute_hive_script",
    description="Execute Hive Script",
    ins={"system_check_output": In(str, description="Output of the system check")},
    out=Out(str, description="Output of the Hive script execution"),
    retry_policy=RetryPolicy(max_retries=0),
)
def execute_hive_script(context, system_check_output):
    """Execute a Hive script using the Hive Local Database."""
    # Example Hive script execution
    result = context.resources.hive_local.run("hive -f /path/to/hive_script.hql")
    return result.stdout.decode("utf-8")

@job(
    name="run_system_check_pipeline",
    description="No description provided.",
    executor_def=in_process_executor,
    resource_defs={"local_shell": fs_io_manager, "hive_local": hive_local},
)
def run_system_check_pipeline():
    """Dagster job to run a system check and execute a Hive script."""
    execute_hive_script(run_system_check())