# Generated by Prefect 2.x Code Generator
# Generation Metadata
# - Date: 2023-10-05
# - Prefect Version: 2.14.0
# - Flow Name: check_pcd_sftp_folder_pipeline
# - Deployment Name: check_pcd_sftp_folder_pipeline_deployment
# - Work Pool: default-agent-pool
# - Task Runner: ConcurrentTaskRunner

from prefect import flow, task, get_run_logger
from prefect.deployments import Deployment
from prefect.orion.schemas.schedules import CronSchedule
from prefect_kubernetes.job import KubernetesJob
from prefect.tasks import task_input_hash
from prefect.infrastructure.process import Process
from prefect.infrastructure.kubernetes import KubernetesJob as KubernetesJobInfra
from prefect.blocks.system import Secret
from prefect import flow, task, get_run_logger

# Schedule Configuration
schedule = CronSchedule(
    cron="{{var.value.pcd_etl_schedule}}",
    timezone="UTC",
    start_date=None,
    end_date=None,
    catchup=False
)

# Task Definitions

@task(retries=0, name="Check PCD SFTP Folder")
def check_pcd_sftp_folder():
    logger = get_run_logger()
    logger.info("Checking PCD SFTP Folder")
    # KubernetesJob configuration
    k8s_job = KubernetesJobInfra(
        namespace="default",
        job_spec={
            "apiVersion": "batch/v1",
            "kind": "Job",
            "metadata": {
                "name": "check-pcd-sftp-folder"
            },
            "spec": {
                "template": {
                    "spec": {
                        "containers": [
                            {
                                "name": "check-pcd-sftp-folder",
                                "image": "your-docker-image:latest",
                                "command": ["python", "check_sftp_folder.py"]
                            }
                        ],
                        "restartPolicy": "Never"
                    }
                }
            }
        }
    )
    k8s_job.run()

@task(retries=0, name="Check PCD Shared Folder")
def check_pcd_shared_folder():
    logger = get_run_logger()
    logger.info("Checking PCD Shared Folder")
    # KubernetesJob configuration
    k8s_job = KubernetesJobInfra(
        namespace="default",
        job_spec={
            "apiVersion": "batch/v1",
            "kind": "Job",
            "metadata": {
                "name": "check-pcd-shared-folder"
            },
            "spec": {
                "template": {
                    "spec": {
                        "containers": [
                            {
                                "name": "check-pcd-shared-folder",
                                "image": "your-docker-image:latest",
                                "command": ["python", "check_shared_folder.py"]
                            }
                        ],
                        "restartPolicy": "Never"
                    }
                }
            }
        }
    )
    k8s_job.run()

@task(retries=0, name="Start PCD Extract 1")
def start_pcd_extract_1():
    logger = get_run_logger()
    logger.info("Starting PCD Extract 1")
    # Process configuration
    process = Process(command=["python", "start_extract_1.py"])
    process.run()

@task(retries=0, name="Parallel HTTP API Extraction")
def parallel_http_api_extraction():
    logger = get_run_logger()
    logger.info("Performing Parallel HTTP API Extraction")
    # Process configuration
    process = Process(command=["python", "parallel_http_api_extraction.py"])
    process.run()

@task(retries=0, name="Start PCD Extract 2")
def start_pcd_extract_2():
    logger = get_run_logger()
    logger.info("Starting PCD Extract 2")
    # Process configuration
    process = Process(command=["python", "start_extract_2.py"])
    process.run()

@task(retries=0, name="PCD File Upload")
def pcd_file_upload():
    logger = get_run_logger()
    logger.info("Uploading PCD File")
    # KubernetesJob configuration
    k8s_job = KubernetesJobInfra(
        namespace="default",
        job_spec={
            "apiVersion": "batch/v1",
            "kind": "Job",
            "metadata": {
                "name": "pcd-file-upload"
            },
            "spec": {
                "template": {
                    "spec": {
                        "containers": [
                            {
                                "name": "pcd-file-upload",
                                "image": "your-docker-image:latest",
                                "command": ["python", "upload_file.py"]
                            }
                        ],
                        "restartPolicy": "Never"
                    }
                }
            }
        }
    )
    k8s_job.run()

@task(retries=0, name="ETL Notification")
def etl_notification():
    logger = get_run_logger()
    logger.info("Sending ETL Notification")
    # Process configuration
    process = Process(command=["python", "send_notification.py"])
    process.run()

# Flow Definition
@flow(name="check_pcd_sftp_folder_pipeline", task_runner="ConcurrentTaskRunner", schedule=schedule)
def check_pcd_sftp_folder_pipeline():
    logger = get_run_logger()
    logger.info("Starting the check_pcd_sftp_folder_pipeline")

    check_sftp_folder = check_pcd_sftp_folder.submit()
    check_shared_folder = check_pcd_shared_folder.submit(wait_for=[check_sftp_folder])
    start_extract_1 = start_pcd_extract_1.submit(wait_for=[check_shared_folder])
    parallel_extraction = parallel_http_api_extraction.submit(wait_for=[start_extract_1])
    start_extract_2 = start_pcd_extract_2.submit(wait_for=[parallel_extraction])
    file_upload = pcd_file_upload.submit(wait_for=[start_extract_2])
    etl_notification.submit(wait_for=[file_upload, check_sftp_folder, check_shared_folder, start_extract_1, parallel_extraction, start_extract_2])

# Deployment Configuration
Deployment(
    name="check_pcd_sftp_folder_pipeline_deployment",
    flow=check_pcd_sftp_folder_pipeline,
    work_pool_name="default-agent-pool",
    work_queue_name="default",
    parameters={},
    tags=[],
    description="Comprehensive Pipeline Description",
    version="1.0.0",
    schedule=schedule
)