# Generated by Dagster code generator on 2024-06-28
# Pipeline: fetch_north_warehouse_csv_pipeline
# Description: No description provided.
# Executor: multiprocess_executor
# Resources: north_warehouse_api, south_warehouse_api, east_warehouse_api, west_warehouse_api

from __future__ import annotations

from typing import Any, Dict, List

from dagster import (
    In,
    Out,
    RetryPolicy,
    ResourceDefinition,
    ScheduleDefinition,
    ScheduleStatus,
    fs_io_manager,
    job,
    op,
    multiprocess_executor,
)


# -------------------------------------------------------------------------
# Resource definitions (placeholders – replace with real implementations)
# -------------------------------------------------------------------------

class WarehouseAPI:
    """Simple placeholder for a warehouse management system API client."""

    def __init__(self, name: str):
        self.name = name

    def fetch_csv(self) -> str:
        """Simulate fetching a CSV string from the warehouse."""
        # In a real implementation this would perform an HTTP request or DB query.
        return f"{self.name}_warehouse_data.csv"

    def normalize_skus(self, csv_path: str) -> List[Dict[str, Any]]:
        """Simulate SKU normalization."""
        # Replace with actual parsing/normalization logic.
        return [{"sku": f"{self.name}_sku_{i}", "quantity": i} for i in range(5)]


def _make_warehouse_resource(name: str) -> ResourceDefinition:
    return ResourceDefinition.hardcoded_resource(WarehouseAPI(name))


# -------------------------------------------------------------------------
# Ops
# -------------------------------------------------------------------------

@op(
    name="Fetch East Warehouse CSV",
    out=Out(str),
    retry_policy=RetryPolicy(max_retries=2),
    description="Fetches the raw CSV file from the East warehouse system.",
)
def fetch_east_warehouse_csv(context) -> str:
    api: WarehouseAPI = context.resources.east_warehouse_api
    csv_path = api.fetch_csv()
    context.log.info(f"Fetched East warehouse CSV at {csv_path}")
    return csv_path


@op(
    name="Fetch North Warehouse CSV",
    out=Out(str),
    retry_policy=RetryPolicy(max_retries=2),
    description="Fetches the raw CSV file from the North warehouse system.",
)
def fetch_north_warehouse_csv(context) -> str:
    api: WarehouseAPI = context.resources.north_warehouse_api
    csv_path = api.fetch_csv()
    context.log.info(f"Fetched North warehouse CSV at {csv_path}")
    return csv_path


@op(
    name="Fetch South Warehouse CSV",
    out=Out(str),
    retry_policy=RetryPolicy(max_retries=2),
    description="Fetches the raw CSV file from the South warehouse system.",
)
def fetch_south_warehouse_csv(context) -> str:
    api: WarehouseAPI = context.resources.south_warehouse_api
    csv_path = api.fetch_csv()
    context.log.info(f"Fetched South warehouse CSV at {csv_path}")
    return csv_path


@op(
    name="Fetch West Warehouse CSV",
    out=Out(str),
    retry_policy=RetryPolicy(max_retries=2),
    description="Fetches the raw CSV file from the West warehouse system.",
)
def fetch_west_warehouse_csv(context) -> str:
    api: WarehouseAPI = context.resources.west_warehouse_api
    csv_path = api.fetch_csv()
    context.log.info(f"Fetched West warehouse CSV at {csv_path}")
    return csv_path


@op(
    name="Normalize East SKUs",
    ins={"csv_path": In(str)},
    out=Out(List[Dict[str, Any]]),
    retry_policy=RetryPolicy(max_retries=2),
    description="Normalizes SKU data from the East warehouse CSV.",
)
def normalize_east_skus(context, csv_path: str) -> List[Dict[str, Any]]:
    api: WarehouseAPI = context.resources.east_warehouse_api
    normalized = api.normalize_skus(csv_path)
    context.log.info(f"Normalized {len(normalized)} East SKUs")
    return normalized


@op(
    name="Normalize North SKUs",
    ins={"csv_path": In(str)},
    out=Out(List[Dict[str, Any]]),
    retry_policy=RetryPolicy(max_retries=2),
    description="Normalizes SKU data from the North warehouse CSV.",
)
def normalize_north_skus(context, csv_path: str) -> List[Dict[str, Any]]:
    api: WarehouseAPI = context.resources.north_warehouse_api
    normalized = api.normalize_skus(csv_path)
    context.log.info(f"Normalized {len(normalized)} North SKUs")
    return normalized


@op(
    name="Normalize South SKUs",
    ins={"csv_path": In(str)},
    out=Out(List[Dict[str, Any]]),
    retry_policy=RetryPolicy(max_retries=2),
    description="Normalizes SKU data from the South warehouse CSV.",
)
def normalize_south_skus(context, csv_path: str) -> List[Dict[str, Any]]:
    api: WarehouseAPI = context.resources.south_warehouse_api
    normalized = api.normalize_skus(csv_path)
    context.log.info(f"Normalized {len(normalized)} South SKUs")
    return normalized


@op(
    name="Normalize West SKUs",
    ins={"csv_path": In(str)},
    out=Out(List[Dict[str, Any]]),
    retry_policy=RetryPolicy(max_retries=2),
    description="Normalizes SKU data from the West warehouse CSV.",
)
def normalize_west_skus(context, csv_path: str) -> List[Dict[str, Any]]:
    api: WarehouseAPI = context.resources.west_warehouse_api
    normalized = api.normalize_skus(csv_path)
    context.log.info(f"Normalized {len(normalized)} West SKUs")
    return normalized


@op(
    name="Reconcile All Inventories",
    ins={
        "north": In(List[Dict[str, Any]]),
        "south": In(List[Dict[str, Any]]),
        "east": In(List[Dict[str, Any]]),
        "west": In(List[Dict[str, Any]]),
    },
    out=Out(List[Dict[str, Any]]),
    retry_policy=RetryPolicy(max_retries=2),
    description="Combines normalized SKU data from all warehouses into a single inventory view.",
)
def reconcile_all_inventories(
    context,
    north: List[Dict[str, Any]],
    south: List[Dict[str, Any]],
    east: List[Dict[str, Any]],
    west: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    combined = north + south + east + west
    context.log.info(f"Reconciled total of {len(combined)} SKU records")
    return combined


@op(
    name="Generate Final Report",
    ins={"inventory": In(List[Dict[str, Any]])},
    out=Out(str),
    retry_policy=RetryPolicy(max_retries=2),
    description="Generates a final report (e.g., CSV path) from the reconciled inventory.",
)
def generate_final_report(context, inventory: List[Dict[str, Any]]) -> str:
    report_path = "final_inventory_report.csv"
    # Placeholder: write CSV logic would go here.
    context.log.info(f"Generated final report at {report_path} with {len(inventory)} records")
    return report_path


# -------------------------------------------------------------------------
# Job definition
# -------------------------------------------------------------------------

@job(
    name="fetch_north_warehouse_csv_pipeline",
    description="No description provided.",
    executor_def=multiprocess_executor,
    resource_defs={
        "north_warehouse_api": _make_warehouse_resource("North"),
        "south_warehouse_api": _make_warehouse_resource("South"),
        "east_warehouse_api": _make_warehouse_resource("East"),
        "west_warehouse_api": _make_warehouse_resource("West"),
        "io_manager": fs_io_manager,
    },
    # The fan-in pattern is expressed via the function arguments below.
)
def fetch_north_warehouse_csv_pipeline():
    # Fetch raw CSVs
    east_csv = fetch_east_warehouse_csv()
    north_csv = fetch_north_warehouse_csv()
    south_csv = fetch_south_warehouse_csv()
    west_csv = fetch_west_warehouse_csv()

    # Normalize each warehouse's data
    east_norm = normalize_east_skus(east_csv)
    north_norm = normalize_north_skus(north_csv)
    south_norm = normalize_south_skus(south_csv)
    west_norm = normalize_west_skus(west_csv)

    # Reconcile inventories
    reconciled = reconcile_all_inventories(
        north=north_norm,
        south=south_norm,
        east=east_norm,
        west=west_norm,
    )

    # Generate final report
    generate_final_report(reconciled)


# -------------------------------------------------------------------------
# Schedule (disabled by default)
# -------------------------------------------------------------------------

daily_schedule = ScheduleDefinition(
    job=fetch_north_warehouse_csv_pipeline,
    cron_schedule="@daily",
    execution_timezone="UTC",
    default_status=ScheduleStatus.STOPPED,
    description="Daily execution of the fetch_north_warehouse_csv_pipeline (disabled by default).",
)